require('dotenv').config();
const express = require('express');
const OpenAI = require('openai');
const { toFile } = require('openai');
const { Pool } = require('pg');
const path = require('path');
const fs = require('fs');

const app = express();
app.use(express.json({ limit: '15mb' }));
app.use(express.static(path.join(__dirname, 'public')));

if (!process.env.OPENAI_API_KEY) {
  console.error('\n❌  OPENAI_API_KEY not found.\n    Copy .env.example to .env and add your key.\n');
  process.exit(1);
}

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// ── Load knowledge base ──
const KB_DIR          = path.join(__dirname, 'kb');
const CORRECTIONS_FILE = path.join(KB_DIR, 'corrections.md');
let salesKB = '';

try { salesKB = fs.readFileSync(path.join(KB_DIR, 'KDK-Sales-Agent-KnowledgeBase.md'), 'utf-8'); }
catch(e) { console.warn('Could not load Sales KB:', e.message); }

// ── Article parser and retrieval ──
const STOPWORDS = new Set([
  'the','to','in','of','and','or','is','are','was','were','how','what','when',
  'where','why','can','do','does','did','have','has','had','be','been','being',
  'will','would','could','should','may','might','shall','for','from','with','at',
  'by','about','as','into','through','before','after','above','below','each',
  'all','both','few','more','most','other','some','such','than','too','very',
  'just','that','this','these','those','a','an','my','your','their','our','its',
  'i','you','he','she','it','we','they','me','him','her','us','them','please',
  'step','steps','using','use','option','click','go','see','get','let','want',
  'need','make','find','know','tell','show','help','like','work','give',
]);

function parseArticles(text, product) {
  const articles = [];
  const parts = text.split(/\n(?=#### \d+\.)/);
  for (const part of parts) {
    const titleMatch = part.match(/#### \d+\.\s*(.+)/);
    if (!titleMatch) continue;
    const title = titleMatch[1].trim();
    const tagsMatch = part.match(/\*\*Tags:\*\*\s*(.+)/);
    const tags = tagsMatch ? tagsMatch[1] : '';
    articles.push({ product, title, tags, content: part.trim() });
  }
  return articles;
}

let allArticles = [];

try {
  const gstFull = fs.readFileSync(path.join(KB_DIR, 'Express-GST-KnowledgeBase.md'), 'utf-8');
  const parsed = parseArticles(gstFull, 'GST');
  allArticles.push(...parsed);
  console.log(`✅  GST KB: ${parsed.length} articles loaded`);
} catch(e) { console.warn('Could not load GST KB:', e.message); }

try {
  const tdsFull = fs.readFileSync(path.join(KB_DIR, 'Express-TDS-KnowledgeBase.md'), 'utf-8');
  const parsed = parseArticles(tdsFull, 'TDS');
  allArticles.push(...parsed);
  console.log(`✅  TDS KB: ${parsed.length} articles loaded`);
} catch(e) { console.warn('Could not load TDS KB:', e.message); }

try {
  const itrFull = fs.readFileSync(path.join(KB_DIR, 'Express-ITR-KnowledgeBase.md'), 'utf-8');
  const parsed = parseArticles(itrFull, 'ITR');
  allArticles.push(...parsed);
  console.log(`✅  ITR KB: ${parsed.length} articles loaded`);
} catch(e) { console.warn('Could not load ITR KB:', e.message); }

console.log(`📚  Total KB articles indexed: ${allArticles.length}`);

// ── Load pre-built embeddings (generated by build_embeddings.js) ──
let embeddedArticles = [];
const EMBEDDINGS_FILE = path.join(__dirname, 'embeddings.json');
try {
  embeddedArticles = JSON.parse(fs.readFileSync(EMBEDDINGS_FILE, 'utf-8'));
  console.log(`🔮  RAG embeddings loaded: ${embeddedArticles.length} articles`);
} catch(e) {
  console.warn('⚠️   embeddings.json not found — using keyword search fallback. Run: node build_embeddings.js');
}

function cosineSim(a, b) {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot   += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

function titleBoost(rawQuery, title) {
  // Split query into individual words, find specific identifiers (GSTR6, 26Q, ITR7, 24Q etc.)
  const words = rawQuery.toLowerCase().split(/[^a-z0-9]+/);
  const titleNorm = title.toLowerCase().replace(/[-\s]+/g, '');
  for (const word of words) {
    // Identifier = word with both letters AND digits (e.g. gstr6, 26q, itr7, 24q, 27eq)
    if (word.length >= 2 && /[a-z]/.test(word) && /\d/.test(word)) {
      if (titleNorm.includes(word)) return 0.18;
    }
  }
  return 0;
}

function retrieveByEmbedding(queryEmbedding, rawQuery = '', maxChars = 8000) {
  const scored = embeddedArticles.map(art => ({
    art,
    score: cosineSim(queryEmbedding, art.embedding) + titleBoost(rawQuery, art.title),
  }));
  scored.sort((a, b) => b.score - a.score);

  let result = '';
  for (const { art, score } of scored) {
    if (score < 0.32) break;
    if (result.length + art.content.length + 6 > maxChars) break;
    result += art.content + '\n\n---\n\n';
  }
  return result;
}

function retrieveByKeyword(query, maxChars = 8000) {
  if (!query || allArticles.length === 0) return '';
  const keywords = query.toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOPWORDS.has(w));
  if (keywords.length === 0) return '';

  const scored = allArticles.map(art => {
    const titleLower   = art.title.toLowerCase();
    const tagsLower    = art.tags.toLowerCase();
    const contentLower = art.content.toLowerCase();
    const score = keywords.reduce((sum, kw) => sum
      + (titleLower.includes(kw)   ? 5 : 0)
      + (tagsLower.includes(kw)    ? 3 : 0)
      + (contentLower.includes(kw) ? 1 : 0), 0);
    return { art, score };
  });
  scored.sort((a, b) => b.score - a.score);

  let result = '';
  for (const { art, score } of scored) {
    if (score === 0) break;
    if (result.length + art.content.length + 6 > maxChars) break;
    result += art.content + '\n\n---\n\n';
  }
  return result;
}

// ── System prompt ──
const BASE_PROMPT = `You are a Sales Consultant from KDK Software's Sales Team. You help prospects discover, evaluate, and experience Express GST, Express TDS, and Express ITR, India's leading cloud-based tax compliance software on the Spectrum Cloud platform.

## YOUR IDENTITY
- You represent KDK Software's Sales Team.
- You communicate like a warm, knowledgeable colleague, not a bot.
- If anyone asks "Are you a bot?", "Are you AI?", "Are you a robot?", or anything similar, deflect naturally and redirect:
  Example: "I'm from KDK's Sales Team! Let me help you find the right solution. What are you looking to achieve?"
- Never volunteer that you are AI, and never claim to be human either, just say you're from KDK Software's Sales Team.

## YOUR PERSONALITY
- Warm, professional, and genuinely helpful
- Confident and persuasive without being aggressive
- Concise: 2 to 4 sections maximum per response. No walls of text. Use short paragraphs.
- Format responses clearly: use **bold** for product names, key features, and important terms. Use bullet lists (- item) when listing 3 or more features, steps, or comparisons. Use numbered lists for step-by-step processes. Use ## Section Name for headings when the response has 2+ distinct sections.
- Keep every response structured: start with the direct answer, then add bullets or short sections only where they help. Avoid unbroken paragraphs longer than 3 lines.
- Respond in the same language the user writes in (Hindi or English). Default is English.
- You deeply understand Indian tax compliance and the challenges of GST/TDS/ITR professionals

## USER CONTEXT
- The user's name and profile (role type) will be provided at the start of the conversation.
- Always address the user by their first name from the very first message.
- If user is a "CA / Tax Professional" → pitch the DIFM (Do It For Me) angle: bulk client management, serving 2x clients, auto notices, single-screen dashboard.
- If user is a "Business / Enterprise" → pitch the DIY (Do It Yourself) angle: automation, error detection, no penalties, anywhere-cloud-access.

## YOUR PRIMARY MISSION
Get the prospect to agree to a free 20-minute product demo. Every conversation moves toward this goal.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## QUALIFYING FLOW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Within the first 1 to 2 exchanges (after greeting), ask qualifying questions naturally, one at a time, not all at once:

Step 1 (if not known from profile): "Are you managing compliance for your own business, or do you handle filings for multiple clients?"
Step 2: "Which area are you looking to streamline, GST, TDS, income tax returns, or all three?"
Step 3: "What's your biggest challenge right now, is it the filing deadlines, reconciliation, or managing notices?"

Use answers to tailor your pitch. Do not bombard with multiple questions at once.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## PRICING, ABSOLUTE NON-NEGOTIABLE RULE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When ANYONE asks about pricing, cost, fees, subscription, plans, or charges:
→ NEVER give any numbers, ranges, or approximate amounts.
→ ALWAYS redirect to a demo. Use language like:
   "The best way to understand the exact fit and investment is to see it live. A 20-minute demo covers everything. Can I set one up for you?"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## DEMO BOOKING, ALWAYS PUSH
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
After EVERY substantive answer, include one brief demo CTA. Examples:
- "Want to see this live? A demo takes just 20 minutes."
- "Shall I set up a quick walkthrough so you can see exactly how this works?"

When a user agrees to a demo or shows strong interest:
1. Respond warmly: e.g., "Perfect! Our team will personally walk you through everything. Just need a couple of quick details."
2. End your message with exactly this token on its own line: COLLECT_DEMO_INFO:true
Do not ask the user for preferred date, preferred time, phone number, or email in the chat message. The website will show a booking card for those details.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## QUICK REPLY SUGGESTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When helpful, suggest 2 to 3 clickable reply options by ending your message with:
QUICK_REPLIES:["Option A","Option B","Option C"]

Use this especially at the start, after open-ended questions, or when the user seems unsure.
Do NOT include both QUICK_REPLIES and COLLECT_DEMO_INFO in the same message. COLLECT_DEMO_INFO takes priority.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## ESCALATION, HUMAN AGENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
If the user asks to speak to a manager, senior, human, or real person, or repeats the same concern more than twice without resolution:
1. Respond warmly and empathetically: "Of course, let me get our senior team connected with you right away."
2. Offer them a quick callback.
3. End your message with exactly this token on its own line: ESCALATE_TO_HUMAN:true
Do NOT include QUICK_REPLIES or COLLECT_DEMO_INFO in the same message as ESCALATE_TO_HUMAN.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## QUICK CALLBACK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When a user says "can someone call me?" or "I prefer a call" or asks for a callback:
1. Confirm warmly that you are arranging it
2. End your message with: OFFER_CALLBACK:true
Do NOT combine this with ESCALATE_TO_HUMAN.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## PROACTIVE DEMO CARD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
After 2-3 exchanges where the user has shown genuine interest and you have a sense of their needs, show the demo booking card proactively. Do NOT ask "would you like to book a demo?" Just show it:
End your message with: SHOW_DEMO_CARD:true
This is the preferred method. Use COLLECT_DEMO_INFO:true only when the user has explicitly said yes to a demo.
Never ask demo scheduling questions in plain chat. Trigger the demo card instead.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## DIY SIZING, BUSINESS/ENTERPRISE USERS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
For Business/Enterprise (DIY) users, gather scale information conversationally to understand their size. Ask ONE question at a time, woven naturally into the chat:

GST: Start with "How many GSTINs are you managing?" then "Roughly how many invoices do you handle a month?" then "How many people in your team would use this?" Also explore: e-invoice, e-way bill, reconciliation, IMS, notice tracker.
TDS: "How many TANs does your business have?" then "How many deductee entries per quarter, roughly?" then Form 16/16A needs.
ITR: "How many ITRs do you file in a year?"

Use answers to size the user and tailor your pitch. Never ask all questions at once.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## YOUR PRODUCTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. **Express GST**, GSTR-1, 3B, 9, 9C filing; 2A/2B reconciliation (no invoice count limit); e-invoice; e-way bill; auto-prepared returns
2. **Express TDS**, 24Q, 26Q, 27Q, 27EQ filing; TRACES integration; TDS certificates; challan management; FVU generation
3. **Express ITR**, ITR-1 to ITR-7; tax audit; AIS/26AS auto-import; e-verification; all income types covered

All products run on **Spectrum Cloud**, fully cloud-based, no local system dependency. VAPT certified, ISO-27001 compliant, 2FA, end-to-end encryption. Mobile app available. Bundle = one login, unified client master, single support team.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## COMPETITOR HANDLING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When prospects mention ClearTax, Winman, GEN TDS, CompuTax, Webtel, Tally, or others:
- Acknowledge respectfully, then point out 2 to 3 specific KDK advantages.
- Never be dismissive or aggressive. Then suggest a demo.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## SALES KNOWLEDGE BASE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${salesKB}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## CONVERSATION STATE — READ BEFORE EVERY REPLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Always scan the full conversation history before replying. The history is ground truth. Never contradict or redo something that is already done:

- DEMO ALREADY BOOKED: If the history contains a demo booking confirmation, NEVER output COLLECT_DEMO_INFO or SHOW_DEMO_CARD. If the user asks about their demo status, confirm it is booked with the date and time from the history. Say "Yes, your demo is confirmed for [date] at [time]" — not "let me get that set up."
- CALLBACK ALREADY ARRANGED: If the history shows a callback was already requested, do not trigger OFFER_CALLBACK again. Acknowledge it.
- ESCALATION ALREADY RAISED: If the history shows the user was already escalated to a human, do not re-escalate. Acknowledge the existing request.
- USER DETAILS ALREADY KNOWN: Name, email, and role were collected before this conversation started. Never ask for them again.
- NEVER APOLOGISE for confusion you did not cause. If the booking or action is clearly in the history, be confident. Do not say "I apologise for the error in my previous message" when no error was made.
- BE CONSISTENT: If you said something in an earlier message, stay consistent with it unless the user has explicitly changed the situation.
- NEVER second-guess the history: If the last assistant message confirmed a demo, that demo is confirmed. Do not contradict it.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## RULES YOU NEVER BREAK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Never give pricing numbers or ranges
- Never make up features not in the knowledge base
- Never give legal or tax advice
- Never go off-topic
- Never be dismissive of competitors
- Never use the em dash or en dash in responses. Write with commas or shorter sentences instead.
- Prefer bullet lists over dense paragraphs when listing 3+ items. Never use more than 6 bullets in a row.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## HOW TO HANDLE FEATURE QUESTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
You have two layers of knowledge:
1. SALES KB (always available) — tells you WHAT features exist and WHY they matter
2. RELEVANT PRODUCT KB ARTICLES (retrieved per question) — gives you the exact HOW (steps, clicks, navigation)

Use them as follows:

IF the RELEVANT PRODUCT KB ARTICLES section has the exact steps → give the steps accurately from the KB. Do not add or invent steps not in the KB.

IF the RELEVANT PRODUCT KB ARTICLES section is empty or does not have the specific steps → use the SALES KB to confidently describe WHAT the feature does and WHY it helps. Do not invent numbered navigation steps (Step 1: Click X, Step 2: Go to Y). Instead say something like: "Yes, Express TDS supports auto-scan for importing client data automatically — it detects your files and pulls them in without manual entry. Want to see exactly how it works in a live demo? It only takes 20 minutes."

NEVER say "I don't know" or "I don't have information" — you always have the Sales KB to fall back on. Always keep the conversation going and drive toward a demo.`;

// ── Reformulate raw feedback into a clean AI-readable rule ──
async function reformulateCorrection(customerQuestion, botResponse, rawFeedback) {
  try {
    const prompt = `You are helping improve the KDK Software Sales Chatbot for KDK Software (Express GST, TDS, ITR products).

A sales team member reviewed a chatbot response and gave raw feedback, it may be in Hindi, English, or mixed, and may be informal or unstructured.

Your job: Convert their feedback into a clear, actionable correction RULE in English that the AI can follow in future conversations.

The rule must:
- Start with "RULE:"
- Be 2-4 sentences max
- Be specific and actionable (tell the AI exactly what to DO, not just what was wrong)
- Include a short example if helpful
- Be in English regardless of feedback language

Context:
Customer question: ${customerQuestion || '(not provided)'}

What Aria responded (the response being corrected):
${(botResponse || '').slice(0, 500)}

Raw feedback from reviewer:
${rawFeedback}

Write ONLY the rule. No preamble, no explanation.`;

    const result = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 180
    });
    return result.choices[0]?.message?.content?.trim() || rawFeedback;
  } catch(e) {
    console.error('Reformulation error:', e.message);
    return rawFeedback;
  }
}

function buildSystemPrompt(retrievedKB) {
  let corrections = '';
  try { corrections = fs.readFileSync(CORRECTIONS_FILE, 'utf-8').trim(); } catch(e) {}

  const kbSection = retrievedKB
    ? `\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n## RELEVANT PRODUCT KB ARTICLES\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nThe following articles are retrieved from the KDK knowledge base specifically for this question. Use ONLY these for step-by-step guidance. Do NOT invent steps not shown here.\n\n${retrievedKB}`
    : `\n\n[SYSTEM NOTE: No specific KB articles retrieved for this question. Use the Sales KB above to describe what features exist and why they help. Do not invent step-by-step navigation. Drive toward a demo.]`;

  const correctionSection = corrections
    ? `\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n## APPROVED CORRECTIONS, HIGHEST PRIORITY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nThese are verified corrections from real sales conversations. They OVERRIDE the general knowledge base when relevant. Always apply them.\n\n${corrections}`
    : '';

  return BASE_PROMPT + kbSection + correctionSection;
}

// ── PostgreSQL setup ──
let pgPool = null;
if (process.env.DATABASE_URL || process.env.DB_HOST) {
  pgPool = new Pool(
    process.env.DATABASE_URL
      ? { connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } }
      : {
          host:     process.env.DB_HOST,
          port:     parseInt(process.env.DB_PORT || '5432'),
          database: process.env.DB_NAME     || 'postgres',
          user:     process.env.DB_USER     || 'postgres',
          password: process.env.DB_PASSWORD || '',
          ssl: { rejectUnauthorized: false },
        }
  );
  pgPool.query(`CREATE TABLE IF NOT EXISTS chat_logs (
      id           SERIAL PRIMARY KEY,
      session_id   VARCHAR(64),
      user_name    VARCHAR(255),
      user_email   VARCHAR(255),
      user_role    VARCHAR(100),
      user_message TEXT NOT NULL,
      bot_response TEXT NOT NULL,
      flagged      BOOLEAN DEFAULT false,
      correction   TEXT,
      created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`)
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS training_feedback (
      id                   SERIAL PRIMARY KEY,
      session_id           VARCHAR(64),
      submitted_by         VARCHAR(255),
      user_role            VARCHAR(100),
      customer_question    TEXT,
      bot_response_given   TEXT,
      wrong_response_desc  TEXT,
      suggested_correction TEXT NOT NULL,
      status               VARCHAR(20) DEFAULT 'pending',
      reviewed_by          VARCHAR(255),
      review_notes         TEXT,
      created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => pgPool.query(`
      ALTER TABLE training_feedback
        ADD COLUMN IF NOT EXISTS customer_question  TEXT,
        ADD COLUMN IF NOT EXISTS bot_response_given TEXT
    `))
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS leads (
      id              BIGINT PRIMARY KEY,
      name            VARCHAR(255) NOT NULL,
      email           VARCHAR(255),
      phone           VARCHAR(50),
      role            VARCHAR(100),
      type            VARCHAR(50)  DEFAULT 'lead',
      time_preference VARCHAR(100),
      source          VARCHAR(100) DEFAULT 'chat-widget',
      created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS demo_requests (
      id              BIGINT PRIMARY KEY,
      name            VARCHAR(255) NOT NULL,
      email           VARCHAR(255),
      phone           VARCHAR(50),
      company         VARCHAR(255),
      role            VARCHAR(100),
      preferred_date  VARCHAR(100),
      time_preference VARCHAR(100),
      booked_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS sessions (
      id         VARCHAR(64) PRIMARY KEY,
      user_data  JSONB DEFAULT '{}',
      messages   JSONB DEFAULT '[]',
      started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      last_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => console.log('✅  PostgreSQL connected — tables ready.'))
    .catch(err => console.error('⚠️  PostgreSQL error:', err.message));
}

async function saveLog({ sessionId, userContext, userMessage, botResponse }) {
  if (!pgPool) return;
  try {
    await pgPool.query(
      `INSERT INTO chat_logs (session_id, user_name, user_email, user_role, user_message, bot_response)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [
        sessionId || null,
        userContext?.name  || null,
        userContext?.email || null,
        userContext?.role  || null,
        userMessage,
        botResponse
      ]
    );
  } catch(err) {
    console.error('Log save error:', err.message);
  }
}

// ── Leads storage ──
const LEADS_FILE = path.join(__dirname, 'leads.json');
let leads = [];
try {
  if (fs.existsSync(LEADS_FILE)) leads = JSON.parse(fs.readFileSync(LEADS_FILE, 'utf-8'));
} catch(e) {}

async function saveLead(lead) {
  leads.push(lead);
  if (pgPool) {
    try {
      await pgPool.query(
        `INSERT INTO leads (id, name, email, phone, role, type, time_preference, source)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING`,
        [lead.id, lead.name, lead.email||null, lead.phone||null, lead.role||null,
         lead.type||'lead', lead.timePreference||null, lead.source||'chat-widget']
      );
    } catch(e) { console.error('Lead PG save error:', e.message); }
  } else {
    try { fs.writeFileSync(LEADS_FILE, JSON.stringify(leads, null, 2)); } catch(e) {}
  }
}

// ── Demo requests storage ──
const DEMOS_FILE = path.join(__dirname, 'demo_requests.json');
let demoRequests = [];
try {
  if (fs.existsSync(DEMOS_FILE)) demoRequests = JSON.parse(fs.readFileSync(DEMOS_FILE, 'utf-8'));
} catch(e) {}

async function saveDemo(demo) {
  demoRequests.push(demo);
  if (pgPool) {
    try {
      await pgPool.query(
        `INSERT INTO demo_requests (id, name, email, phone, company, role, preferred_date, time_preference)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING`,
        [demo.id, demo.name, demo.email||null, demo.phone||null, demo.company||null,
         demo.role||null, demo.preferredDate||null, demo.timePreference||null]
      );
    } catch(e) { console.error('Demo PG save error:', e.message); }
  } else {
    try { fs.writeFileSync(DEMOS_FILE, JSON.stringify(demoRequests, null, 2)); } catch(e) {}
  }
}

// ── Sessions storage ──
let sessionStore = {};
try {
  const SESSIONS_FILE = path.join(__dirname, 'sessions.json');
  if (fs.existsSync(SESSIONS_FILE)) {
    const arr = JSON.parse(fs.readFileSync(SESSIONS_FILE, 'utf-8'));
    arr.forEach(s => { sessionStore[s.id] = s; });
  }
} catch(e) {}

async function saveSession(sess) {
  sessionStore[sess.id] = sess;
  if (pgPool) {
    try {
      await pgPool.query(
        `INSERT INTO sessions (id, user_data, messages, started_at, last_at)
         VALUES ($1,$2,$3,$4,$5)
         ON CONFLICT (id) DO UPDATE SET
           user_data  = EXCLUDED.user_data,
           messages   = EXCLUDED.messages,
           last_at    = EXCLUDED.last_at`,
        [sess.id, JSON.stringify(sess.user||{}), JSON.stringify(sess.messages||[]),
         sess.startedAt, sess.lastAt]
      );
    } catch(e) { console.error('Session PG save error:', e.message); }
  }
}

// ── File-based Feedback storage ──
const FEEDBACK_FILE = path.join(__dirname, 'feedback.json');
let feedbackList = [];

try {
  if (fs.existsSync(FEEDBACK_FILE)) {
    feedbackList = JSON.parse(fs.readFileSync(FEEDBACK_FILE, 'utf-8'));
  }
} catch(e) {}

function saveFeedback() {
  try {
    fs.writeFileSync(FEEDBACK_FILE, JSON.stringify(feedbackList, null, 2));
  } catch(e) {}
}

// ── Routes ──

// Chat (streaming SSE)
app.post('/api/chat', async (req, res) => {
  const { messages, userContext, sessionId } = req.body;
  if (!Array.isArray(messages)) return res.status(400).json({ error: 'Invalid messages' });

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');

  // Build context-aware message list
  const contextMessages = [];
  if (userContext && userContext.name) {
    const firstName = userContext.name.split(' ')[0];
    const roleDesc = userContext.role === 'CA / Tax Professional'
      ? 'a CA / Tax Professional who manages compliance for multiple clients (DIFM)'
      : 'a business owner managing their own company compliance (DIY)';
    let demoNote = '';
    if (userContext.demoBooked && userContext.bookedDemoDetails) {
      demoNote = ` IMPORTANT: This user has ALREADY BOOKED A DEMO for ${userContext.bookedDemoDetails.date} at ${userContext.bookedDemoDetails.time}. Do NOT output COLLECT_DEMO_INFO or SHOW_DEMO_CARD. Do NOT ask them to fill a demo form. If they ask about their demo status, simply confirm it is booked.`;
    }
    contextMessages.push({
      role: 'user',
      content: `[System context, do not repeat this to the user: The person I am speaking with is ${userContext.name} (address them as "${firstName}"). They are ${roleDesc}. Their email is ${userContext.email}.${demoNote} Tailor all responses to their profile.]`
    });
    contextMessages.push({
      role: 'assistant',
      content: `[Understood. I will address this person as ${firstName}, pitch the appropriate angle for their role, and guide them toward a demo.${userContext.demoBooked ? ' Their demo is already booked — I will not trigger COLLECT_DEMO_INFO or SHOW_DEMO_CARD.' : ''}]`
    });
  }

  try {
    const lastUserMsg = messages[messages.length - 1]?.content || '';

    // Build a context-enriched query: last message + previous user message for better RAG on follow-ups
    const prevUserMsgs = messages.slice(-6).filter(m => m.role === 'user');
    const prevUserMsg  = prevUserMsgs.length >= 2 ? prevUserMsgs[prevUserMsgs.length - 2].content : '';
    const contextQuery = prevUserMsg ? `${prevUserMsg} ${lastUserMsg}` : lastUserMsg;

    // Retrieve relevant KB articles — use RAG if embeddings loaded, else keyword fallback
    let retrievedKB = '';
    if (embeddedArticles.length > 0) {
      try {
        // First try: embed last message only
        const embRes = await openai.embeddings.create({
          model: 'text-embedding-3-small',
          input: lastUserMsg,
        });
        retrievedKB = retrieveByEmbedding(embRes.data[0].embedding, lastUserMsg);

        // Second try: if no results, embed with conversation context
        if (!retrievedKB && prevUserMsg) {
          const embRes2 = await openai.embeddings.create({
            model: 'text-embedding-3-small',
            input: contextQuery,
          });
          retrievedKB = retrieveByEmbedding(embRes2.data[0].embedding, contextQuery);
        }
      } catch(embErr) {
        console.warn('Embedding call failed, falling back to keyword search:', embErr.message);
        retrievedKB = retrieveByKeyword(contextQuery);
      }
    } else {
      retrievedKB = retrieveByKeyword(contextQuery);
    }

    const stream = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      messages: [
        { role: 'system', content: buildSystemPrompt(retrievedKB) },
        ...contextMessages,
        ...messages.slice(-24)
      ],
      stream: true,
      temperature: 0.5,
      max_tokens: 500
    });

    let fullResponse = '';
    for await (const chunk of stream) {
      const text = chunk.choices[0]?.delta?.content || '';
      if (text) {
        fullResponse += text;
        res.write(`data: ${JSON.stringify({ text })}\n\n`);
      }
    }
    res.write('data: [DONE]\n\n');
    res.end();

    const userMessage = messages[messages.length - 1]?.content || '';
    saveLog({ sessionId, userContext, userMessage, botResponse: fullResponse });

    if (sessionId) {
      const now = new Date().toISOString();
      if (!sessionStore[sessionId]) {
        sessionStore[sessionId] = { id: sessionId, user: userContext || {}, messages: [], startedAt: now, lastAt: now };
      }
      const sess = sessionStore[sessionId];
      if (userContext?.name && !sess.user?.name) sess.user = userContext;
      const lastTwo = sess.messages.slice(-2);
      if (!lastTwo.some(m => m.role === 'user' && m.content === userMessage)) {
        sess.messages.push({ role: 'user', content: userMessage, ts: now });
        sess.messages.push({ role: 'assistant', content: fullResponse, ts: new Date().toISOString() });
      }
      sess.lastAt = new Date().toISOString();
      saveSession(sess);
    }
  } catch (err) {
    console.error('OpenAI error:', err.message);
    const msg = err.status === 429
      ? 'Too many requests, please wait a moment and try again.'
      : 'Something went wrong. Please try again.';
    res.write(`data: ${JSON.stringify({ error: msg })}\n\n`);
    res.end();
  }
});

// Save lead (pre-chat form)
app.post('/api/save-lead', async (req, res) => {
  const { name, email, role } = req.body;
  if (!name?.trim() || !email?.trim()) {
    return res.status(400).json({ error: 'Name and email are required' });
  }
  const lead = {
    id: Date.now(),
    name: name.trim(),
    email: email.trim().toLowerCase(),
    role: role?.trim() || 'Unknown',
    source: 'chat-widget',
    capturedAt: new Date().toISOString()
  };
  await saveLead(lead);
  console.log(`\n📧 Lead captured: ${lead.name} <${lead.email}> — ${lead.role}`);
  res.json({ success: true, id: lead.id });
});

// Book demo
app.post('/api/book-demo', async (req, res) => {
  const { name, email, phone, company, preferredDate, timePreference, role } = req.body;
  if (!name?.trim() || !phone?.trim()) {
    return res.status(400).json({ error: 'Name and phone are required' });
  }
  const demo = {
    id: Date.now(),
    name: name.trim(),
    email: email?.trim().toLowerCase() || '',
    phone: phone.trim(),
    company: company?.trim() || '',
    role: role?.trim() || '',
    preferredDate: preferredDate || '',
    timePreference: timePreference || 'Not specified',
    bookedAt: new Date().toISOString()
  };
  await saveDemo(demo);
  console.log(`\n📅 Demo booked: ${demo.name} (${demo.phone}) ${demo.email ? '<' + demo.email + '>' : ''} — ${demo.preferredDate} ${demo.timePreference}`);
  res.json({ success: true, id: demo.id });
});

// Callback / escalation request
app.post('/api/request-callback', async (req, res) => {
  const { name, phone, timePreference, type, role } = req.body;
  if (!name?.trim() || !phone?.trim()) {
    return res.status(400).json({ error: 'Name and phone are required' });
  }
  const entry = {
    id: Date.now(),
    name: name.trim(),
    phone: phone.trim(),
    type: type || 'callback',
    role: role || '',
    timePreference: timePreference || 'Not specified',
    source: 'chat-widget',
    requestedAt: new Date().toISOString()
  };
  await saveLead(entry);
  console.log(`\n📞 Callback requested [${entry.type}]: ${entry.name} (${entry.phone})`);
  res.json({ success: true, id: entry.id });
});

// Demo count
app.get('/api/demos/count', async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT COUNT(*) FROM demo_requests');
      return res.json({ count: parseInt(r.rows[0].count) });
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  res.json({ count: demoRequests.length });
});

// All demos (for review)
app.get('/api/demos', async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM demo_requests ORDER BY booked_at DESC');
      return res.json(r.rows);
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  res.json(demoRequests);
});

// All leads (for review)
app.get('/api/leads', async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM leads ORDER BY created_at DESC');
      return res.json(r.rows);
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  res.json(leads);
});

// Chat logs (for reviewing bot quality)
app.get('/api/logs', async (req, res) => {
  if (!pgPool) return res.json({ error: 'PostgreSQL not configured', logs: [] });
  try {
    const limit  = Math.min(parseInt(req.query.limit  || '100'), 500);
    const offset = parseInt(req.query.offset || '0');
    const flagged = req.query.flagged === 'true';

    const where = flagged ? 'WHERE flagged = true' : '';
    const result = await pgPool.query(
      `SELECT id, session_id, user_name, user_role, user_message, bot_response, flagged, correction, created_at
       FROM chat_logs ${where}
       ORDER BY created_at DESC
       LIMIT $1 OFFSET $2`,
      [limit, offset]
    );
    res.json({ count: result.rowCount, logs: result.rows });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Session routes ──
app.get('/api/sessions', async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM sessions ORDER BY last_at DESC');
      const sessions = r.rows.map(row => ({
        id: row.id, user: row.user_data, messages: row.messages,
        startedAt: row.started_at, lastAt: row.last_at
      }));
      return res.json({ count: sessions.length, sessions });
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  const sessions = Object.values(sessionStore).sort((a, b) => b.lastAt > a.lastAt ? 1 : -1);
  res.json({ count: sessions.length, sessions });
});

app.get('/api/sessions/:id', async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM sessions WHERE id = $1', [req.params.id]);
      if (!r.rows.length) return res.status(404).json({ error: 'Not found' });
      const row = r.rows[0];
      return res.json({ id: row.id, user: row.user_data, messages: row.messages,
        startedAt: row.started_at, lastAt: row.last_at });
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  const session = sessionStore[req.params.id];
  if (!session) return res.status(404).json({ error: 'Not found' });
  res.json(session);
});

// ── Training Feedback routes ──

// Save training feedback from sales team
app.post('/api/training-feedback', async (req, res) => {
  const { sessionId, submittedBy, userRole, customerQuestion, botResponseGiven, suggestedCorrection } = req.body;
  if (!suggestedCorrection?.trim()) {
    return res.status(400).json({ error: 'Suggested correction is required' });
  }

  const entry = {
    id: Date.now(),
    sessionId: sessionId || null,
    submittedBy: submittedBy || null,
    userRole: userRole || null,
    customerQuestion: customerQuestion || null,
    botResponseGiven: botResponseGiven || null,
    suggestedCorrection: suggestedCorrection.trim(),
    status: 'pending',
    reviewedBy: null,
    reviewNotes: null,
    createdAt: new Date().toISOString()
  };
  feedbackList.push(entry);
  saveFeedback();
  console.log(`\n📝 Training feedback #${entry.id} by ${submittedBy || 'unknown'}`);

  if (pgPool) {
    pgPool.query(
      `INSERT INTO training_feedback
         (session_id, submitted_by, user_role, customer_question, bot_response_given, wrong_response_desc, suggested_correction)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [sessionId||null, submittedBy||null, userRole||null, customerQuestion||null, botResponseGiven||null, botResponseGiven||null, suggestedCorrection.trim()]
    ).catch(err => console.error('PG feedback save error:', err.message));
  }

  res.json({ success: true, id: entry.id });
});

// View all training feedback (admin)
app.get('/api/training-feedback', async (req, res) => {
  if (!pgPool) {
    const { status } = req.query;
    const allowed = ['pending', 'approved', 'rejected'];
    const list = allowed.includes(status) ? feedbackList.filter(f => f.status === status) : feedbackList;
    return res.json({ count: list.length, feedback: [...list].sort((a, b) => b.id - a.id) });
  }
  try {
    const { status } = req.query;
    const allowed = ['pending', 'approved', 'rejected'];
    const where  = allowed.includes(status) ? 'WHERE status = $1' : '';
    const params = allowed.includes(status) ? [status] : [];
    const result = await pgPool.query(
      `SELECT id, session_id, submitted_by, user_role, customer_question, bot_response_given,
              wrong_response_desc, suggested_correction, status, reviewed_by, review_notes, created_at
       FROM training_feedback ${where} ORDER BY created_at DESC`,
      params
    );
    res.json({ count: result.rowCount, feedback: result.rows });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// Approve or reject a feedback entry
app.post('/api/training-feedback/:id/review', async (req, res) => {
  const { status, reviewedBy, reviewNotes } = req.body;
  if (!['approved', 'rejected'].includes(status)) {
    return res.status(400).json({ error: 'status must be approved or rejected' });
  }

  if (!pgPool) {
    const id = parseInt(req.params.id);
    const entry = feedbackList.find(f => f.id === id);
    if (!entry) return res.status(404).json({ error: 'Not found' });
    entry.status = status;
    entry.reviewedBy = reviewedBy || null;
    entry.reviewNotes = reviewNotes || null;
    saveFeedback();
    if (status === 'approved') {
      const rule = await reformulateCorrection(entry.customerQuestion, entry.botResponseGiven, entry.suggestedCorrection);
      const date = new Date().toISOString().split('T')[0];
      const by   = reviewedBy ? ` | Reviewed by: ${reviewedBy}` : '';
      const q    = entry.customerQuestion ? `\n**Customer asked:** ${entry.customerQuestion}` : '';
      const b    = entry.botResponseGiven ? `\n**Bot responded:** ${entry.botResponseGiven.slice(0, 400)}` : '';
      const line = `\n---\n\n[Correction #${entry.id} | ${date}${by}]${q}${b}\n**AI Rule:**\n${rule}\n`;
      fs.appendFileSync(CORRECTIONS_FILE, line, 'utf-8');
      console.log(`\n✅ Correction #${entry.id} reformulated and written to corrections.md — live immediately.`);
    }
    return res.json({ success: true });
  }

  try {
    const fetch_result = await pgPool.query('SELECT * FROM training_feedback WHERE id = $1', [req.params.id]);
    if (!fetch_result.rows.length) return res.status(404).json({ error: 'Not found' });
    const entry = fetch_result.rows[0];

    await pgPool.query(
      `UPDATE training_feedback SET status = $1, reviewed_by = $2, review_notes = $3 WHERE id = $4`,
      [status, reviewedBy || null, reviewNotes || null, req.params.id]
    );

    if (status === 'approved') {
      const rule = await reformulateCorrection(entry.customer_question, entry.bot_response_given, entry.suggested_correction);
      const date = new Date().toISOString().split('T')[0];
      const by   = reviewedBy ? ` | Reviewed by: ${reviewedBy}` : '';
      const q    = entry.customer_question  ? `\n**Customer asked:** ${entry.customer_question}` : '';
      const b    = entry.bot_response_given ? `\n**Bot responded:** ${entry.bot_response_given.slice(0, 400)}` : '';
      const line = `\n---\n\n[Correction #${entry.id} | ${date}${by}]${q}${b}\n**AI Rule:**\n${rule}\n`;
      fs.appendFileSync(CORRECTIONS_FILE, line, 'utf-8');
      console.log(`\n✅ Correction #${entry.id} reformulated and written to corrections.md — live immediately.`);
    }

    res.json({ success: true });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// Flag a log entry as wrong and optionally add correction
app.post('/api/logs/:id/flag', async (req, res) => {
  if (!pgPool) return res.status(503).json({ error: 'PostgreSQL not configured' });
  const { correction } = req.body;
  try {
    await pgPool.query(
      'UPDATE chat_logs SET flagged = true, correction = $1 WHERE id = $2',
      [correction || null, req.params.id]
    );
    res.json({ success: true });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Voice Transcription (OpenAI Whisper) ──
app.post('/api/voice-transcribe', async (req, res) => {
  try {
    const { audio, mimeType = 'audio/webm' } = req.body;
    if (!audio) return res.status(400).json({ error: 'No audio data provided' });

    const buffer = Buffer.from(audio, 'base64');
    const ext = mimeType.includes('mp4') ? 'mp4' : mimeType.includes('ogg') ? 'ogg' : 'webm';
    const file = await toFile(buffer, `recording.${ext}`, { type: mimeType });

    const transcription = await openai.audio.transcriptions.create({
      file,
      model: 'whisper-1',
    });

    res.json({ text: transcription.text });
  } catch (e) {
    console.error('Voice transcription error:', e.message);
    res.status(500).json({ error: 'Transcription failed. Please type instead.' });
  }
});

app.post('/api/tts', async (req, res) => {
  try {
    const { text } = req.body;
    if (!text) return res.status(400).json({ error: 'No text provided' });

    const mp3 = await openai.audio.speech.create({
      model: 'tts-1',
      voice: 'nova',   // female, warm, friendly
      input: text,
      speed: 1.0,
    });

    const buffer = Buffer.from(await mp3.arrayBuffer());
    res.set('Content-Type', 'audio/mpeg');
    res.send(buffer);
  } catch (e) {
    console.error('TTS error:', e.message);
    res.status(500).json({ error: 'TTS failed' });
  }
});

// Fallback
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`\n✅  KDK Sales Chatbot is live!`);
  console.log(`   Open: http://localhost:${PORT}\n`);
});
