require('dotenv').config();
const express = require('express');
const OpenAI = require('openai');
const { toFile } = require('openai');
const { Pool } = require('pg');
const path = require('path');
const fs = require('fs');

const app = express();
app.use(express.json({ limit: '15mb' }));
app.use(express.static(path.join(__dirname, 'public')));

if (!process.env.OPENAI_API_KEY) {
  console.error('\n❌  OPENAI_API_KEY not found.\n    Copy .env.example to .env and add your key.\n');
  process.exit(1);
}

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// ── Corrections cache — avoids disk I/O on every request ──
let correctionsCache = '';
let correctionsMtime  = 0;
function reloadCorrections() {
  try {
    const stat = fs.statSync(CORRECTIONS_FILE);
    if (stat.mtimeMs !== correctionsMtime) {
      correctionsCache = fs.readFileSync(CORRECTIONS_FILE, 'utf-8').trim();
      correctionsMtime  = stat.mtimeMs;
      console.log('🔄  corrections.md reloaded');
    }
  } catch(e) { /* file may not exist yet */ }
}
setInterval(reloadCorrections, 10000); // poll every 10 s

// ── In-memory rate limiter ──
const _rlMap = new Map();
function checkRateLimit(key, windowMs, max) {
  const now = Date.now();
  const e   = _rlMap.get(key) || { n: 0, reset: now + windowMs };
  if (now > e.reset) { e.n = 0; e.reset = now + windowMs; }
  e.n++;
  _rlMap.set(key, e);
  return e.n <= max;
}
setInterval(() => { const now = Date.now(); for (const [k, e] of _rlMap) if (now > e.reset) _rlMap.delete(k); }, 300000);

// ── Admin route protection ──
if (!process.env.ADMIN_TOKEN) {
  console.warn('⚠️   ADMIN_TOKEN not set — admin routes are unprotected. Add ADMIN_TOKEN=<secret> to .env to secure them.');
}
function requireAdmin(req, res, next) {
  if (!process.env.ADMIN_TOKEN) return next();
  const token = req.headers['x-admin-token'] || req.query.token;
  if (token !== process.env.ADMIN_TOKEN) return res.status(403).json({ error: 'Unauthorized' });
  next();
}

// ── Load knowledge base ──
const KB_DIR          = path.join(__dirname, 'kb');
const CORRECTIONS_FILE = path.join(KB_DIR, 'corrections.md');
let salesKB = '';

try { salesKB = fs.readFileSync(path.join(KB_DIR, 'KDK-Sales-Agent-KnowledgeBase.md'), 'utf-8'); }
catch(e) { console.warn('Could not load Sales KB:', e.message); }

// ── Article parser and retrieval ──
const STOPWORDS = new Set([
  'the','to','in','of','and','or','is','are','was','were','how','what','when',
  'where','why','can','do','does','did','have','has','had','be','been','being',
  'will','would','could','should','may','might','shall','for','from','with','at',
  'by','about','as','into','through','before','after','above','below','each',
  'all','both','few','more','most','other','some','such','than','too','very',
  'just','that','this','these','those','a','an','my','your','their','our','its',
  'i','you','he','she','it','we','they','me','him','her','us','them','please',
  'step','steps','using','use','option','click','go','see','get','let','want',
  'need','make','find','know','tell','show','help','like','work','give',
]);

function parseArticles(text, product) {
  const articles = [];
  const parts = text.split(/\n(?=#### \d+\.)/);
  for (const part of parts) {
    const titleMatch = part.match(/#### \d+\.\s*(.+)/);
    if (!titleMatch) continue;
    const title = titleMatch[1].trim();
    const tagsMatch = part.match(/\*\*Tags:\*\*\s*(.+)/);
    const tags = tagsMatch ? tagsMatch[1] : '';
    articles.push({ product, title, tags, content: part.trim() });
  }
  return articles;
}

let allArticles = [];

try {
  const gstFull = fs.readFileSync(path.join(KB_DIR, 'Express-GST-KnowledgeBase.md'), 'utf-8');
  const parsed = parseArticles(gstFull, 'GST');
  allArticles.push(...parsed);
  console.log(`✅  GST KB: ${parsed.length} articles loaded`);
} catch(e) { console.warn('Could not load GST KB:', e.message); }

try {
  const tdsFull = fs.readFileSync(path.join(KB_DIR, 'Express-TDS-KnowledgeBase.md'), 'utf-8');
  const parsed = parseArticles(tdsFull, 'TDS');
  allArticles.push(...parsed);
  console.log(`✅  TDS KB: ${parsed.length} articles loaded`);
} catch(e) { console.warn('Could not load TDS KB:', e.message); }

try {
  const itrFull = fs.readFileSync(path.join(KB_DIR, 'Express-ITR-KnowledgeBase.md'), 'utf-8');
  const parsed = parseArticles(itrFull, 'ITR');
  allArticles.push(...parsed);
  console.log(`✅  ITR KB: ${parsed.length} articles loaded`);
} catch(e) { console.warn('Could not load ITR KB:', e.message); }

console.log(`📚  Total KB articles indexed: ${allArticles.length}`);

// ── Load pre-built embeddings (generated by build_embeddings.js) ── // Merge happens after both are loaded — see mergeEmbeddingsIntoArticles() call below
let embeddedArticles = [];
const EMBEDDINGS_FILE = path.join(__dirname, 'embeddings.json');
try {
  embeddedArticles = JSON.parse(fs.readFileSync(EMBEDDINGS_FILE, 'utf-8'));
  console.log(`🔮  RAG embeddings loaded: ${embeddedArticles.length} articles`);
} catch(e) {
  console.warn('⚠️   embeddings.json not found — using keyword search fallback. Run: node build_embeddings.js');
}

// ── Merge embeddings into allArticles for hybrid retrieval ──
// Attaches the embedding vector from embeddings.json to each matching article in allArticles,
// keyed by product+title. This gives retrieveHybrid() a single unified article set to score.
{
  const map = new Map();
  for (const ea of embeddedArticles) map.set(`${ea.product}:${ea.title}`, ea.embedding);
  let matched = 0;
  for (const art of allArticles) {
    const emb = map.get(`${art.product}:${art.title}`);
    if (emb) { art.embedding = emb; matched++; }
  }
  if (embeddedArticles.length > 0) console.log(`🔗  Merged embeddings: ${matched}/${allArticles.length} articles have vectors`);
}

function cosineSim(a, b) {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot   += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

function titleBoost(rawQuery, title) {
  // Split query into individual words, find specific identifiers (GSTR6, 26Q, ITR7, 24Q etc.)
  const words = rawQuery.toLowerCase().split(/[^a-z0-9]+/);
  const titleNorm = title.toLowerCase().replace(/[-\s]+/g, '');
  for (const word of words) {
    // Identifier = word with both letters AND digits (e.g. gstr6, 26q, itr7, 24q, 27eq)
    if (word.length >= 2 && /[a-z]/.test(word) && /\d/.test(word)) {
      if (titleNorm.includes(word)) return 0.18;
    }
  }
  return 0;
}

// Detect which product the user is focused on from the conversation history.
// Returns 'GST', 'TDS', 'ITR', or null (unknown/mixed).
// Only scans USER messages — bot's Q2 always mentions all three, which creates false ties.
function detectProductContext(messages) {
  const userText = messages.filter(m => m.role === 'user').map(m => m.content || '').join(' ');
  // Explicit multi-product signals → null (covers "all", "all three", "a mix", "all my clients")
  if (/\ball\b|\ba mix\b|\ball three\b/i.test(userText)) return null;
  const gst = (userText.match(/\bgst\b/gi) || []).length;
  const tds = (userText.match(/\btds\b/gi) || []).length;
  const itr = (userText.match(/\bitr\b/gi) || []).length;
  const max = Math.max(gst, tds, itr);
  if (max === 0) return null;
  // Only declare a winner if it has a clear majority — tie means mixed context
  if (gst === max && gst > tds && gst > itr) return 'GST';
  if (tds === max && tds > gst && tds > itr) return 'TDS';
  if (itr === max && itr > gst && itr > tds) return 'ITR';
  return null;
}

function retrieveByEmbedding(queryEmbedding, rawQuery = '', maxChars = 4000, productFilter = null) {
  // When product context is known, score articles from that product higher (+0.12 boost).
  // This prevents, e.g., an ITR ClearTax migration article from outranking the GST one.
  const scored = embeddedArticles.map(art => ({
    art,
    score: cosineSim(queryEmbedding, art.embedding)
      + titleBoost(rawQuery, art.title)
      + (productFilter && art.product === productFilter ? 0.12 : 0),
  }));
  scored.sort((a, b) => b.score - a.score);

  let result = '';

  if (!productFilter) {
    // No product specified — pick the best matching article from each product so the AI
    // can answer for GST, TDS, and ITR rather than defaulting to whichever scores highest globally.
    const seen = {};
    for (const { art, score } of scored) {
      if (score < 0.32) break;
      if (seen[art.product]) continue;
      if (result.length + art.content.length + 6 > maxChars) continue;
      result += art.content + '\n\n---\n\n';
      seen[art.product] = true;
      if (Object.keys(seen).length === 3) break;
    }
    return result;
  }

  for (const { art, score } of scored) {
    if (score < 0.32) break;
    if (result.length + art.content.length + 6 > maxChars) break;
    result += art.content + '\n\n---\n\n';
  }
  return result;
}

function retrieveByKeyword(query, maxChars = 4000, productFilter = null) {
  if (!query || allArticles.length === 0) return '';
  const keywords = query.toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOPWORDS.has(w));
  if (keywords.length === 0) return '';

  // Also match stemmed singular/plural — e.g. "clients" matches "client" and vice versa
  const expandedKeywords = [...new Set(keywords.flatMap(kw => {
    if (kw.endsWith('s') && kw.length > 4) return [kw, kw.slice(0, -1)]; // clients → client
    return [kw, kw + 's'];                                                 // client → clients
  }))];

  const scored = allArticles.map(art => {
    const titleLower   = art.title.toLowerCase();
    const tagsLower    = art.tags.toLowerCase();
    const contentLower = art.content.toLowerCase();
    const score = expandedKeywords.reduce((sum, kw) => sum
      + (titleLower.includes(kw)   ? 5 : 0)
      + (tagsLower.includes(kw)    ? 3 : 0)
      + (contentLower.includes(kw) ? 1 : 0), 0)
      + (productFilter && art.product === productFilter ? 4 : 0); // boost matching product
    return { art, score };
  });
  scored.sort((a, b) => b.score - a.score);

  let result = '';

  if (!productFilter) {
    // No product specified — pick the best article from each product.
    const seen = {};
    for (const { art, score } of scored) {
      if (score < 3) break;
      if (seen[art.product]) continue;
      if (result.length + art.content.length + 6 > maxChars) continue;
      result += art.content + '\n\n---\n\n';
      seen[art.product] = true;
      if (Object.keys(seen).length === 3) break;
    }
    return result;
  }

  for (const { art, score } of scored) {
    if (score < 3) break;
    if (result.length + art.content.length + 6 > maxChars) break;
    result += art.content + '\n\n---\n\n';
  }
  return result;
}

// ── Hybrid retrieval: combines embedding cosine similarity + keyword scoring ──
// Always runs both methods and merges scores so neither alone can return a wrong article.
// Keyword component is weighted higher (0.6) because exact term matches (gstr1, books, etc.)
// are more reliable than semantic similarity for domain-specific documentation queries.
function retrieveHybrid(queryEmbedding, rawQuery, maxChars = 4000, productFilter = null) {
  if (allArticles.length === 0) return '';

  // Keyword scoring (reuse same logic as retrieveByKeyword)
  const keywords = rawQuery.toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOPWORDS.has(w));
  const expandedKeywords = keywords.length === 0 ? [] : [...new Set(keywords.flatMap(kw =>
    (kw.endsWith('s') && kw.length > 4) ? [kw, kw.slice(0, -1)] : [kw, kw + 's']
  ))];
  const maxKwScore = expandedKeywords.length * 9; // max possible keyword score per article (title+tags+content)

  const scored = allArticles.map(art => {
    // Keyword score
    let kwScore = 0;
    if (expandedKeywords.length > 0) {
      const titleLower   = art.title.toLowerCase();
      const tagsLower    = art.tags.toLowerCase();
      const contentLower = art.content.toLowerCase();
      kwScore = expandedKeywords.reduce((sum, kw) => sum
        + (titleLower.includes(kw)   ? 5 : 0)
        + (tagsLower.includes(kw)    ? 3 : 0)
        + (contentLower.includes(kw) ? 1 : 0), 0)
        + (productFilter && art.product === productFilter ? 4 : 0);
    }

    // Embedding score (0 if no embedding available for this article)
    let embScore = 0;
    if (queryEmbedding && art.embedding) {
      embScore = cosineSim(queryEmbedding, art.embedding)
        + titleBoost(rawQuery, art.title)
        + (productFilter && art.product === productFilter ? 0.12 : 0);
    }

    // Hybrid: keyword-dominant (0.6) + embedding (0.4)
    const normKw = maxKwScore > 0 ? kwScore / maxKwScore : 0;
    const hybrid = embScore * 0.4 + normKw * 0.6;
    return { art, hybrid };
  });

  scored.sort((a, b) => b.hybrid - a.hybrid);

  const THRESHOLD = 0.20; // combined score floor — keyword alone at 1/3 max passes, embedding alone needs ~0.50
  let result = '';

  if (!productFilter) {
    const seen = {};
    for (const { art, hybrid } of scored) {
      if (hybrid < THRESHOLD) break;
      if (seen[art.product]) continue;
      if (result.length + art.content.length + 6 > maxChars) continue;
      result += art.content + '\n\n---\n\n';
      seen[art.product] = true;
      if (Object.keys(seen).length === 3) break;
    }
    return result;
  }

  for (const { art, hybrid } of scored) {
    if (hybrid < THRESHOLD) break;
    if (result.length + art.content.length + 6 > maxChars) break;
    result += art.content + '\n\n---\n\n';
  }
  return result;
}

// ── System prompt ──
const BASE_PROMPT = `You are a Sales Consultant from KDK Software's Sales Team. You help prospects discover, evaluate, and experience Express GST, Express TDS, and Express ITR, India's leading cloud-based tax compliance software on the Spectrum Cloud platform.

## YOUR IDENTITY
- You represent KDK Software's Sales Team.
- You communicate like a warm, knowledgeable colleague, not a bot.
- If anyone asks "Are you a bot?", "Are you AI?", "Are you a robot?", or anything similar, deflect naturally and redirect:
  Example: "I'm from KDK's Sales Team! Let me help you find the right solution. What are you looking to achieve?"
- Never volunteer that you are AI, and never claim to be human either, just say you're from KDK Software's Sales Team.

## YOUR PERSONALITY
- Warm, professional, and genuinely helpful
- Confident and persuasive without being aggressive
- Concise: most replies should be 2-4 short sentences. Think chat message, not email.
- Use **bold** for product names and key feature names only.
- Use a bullet list ONLY when listing 3+ distinct features or options — and keep each bullet to one line.
- Use numbered steps ONLY when the user explicitly asked for a process (see HOW TO ANSWER QUESTIONS below).
- Never use section headings (##) in a reply unless the response genuinely has two completely separate topics.
- Never write sub-bullets. Never expand a bullet into a paragraph.
- Respond in the same language the user uses: English, Hindi, or Hinglish (mixed Hindi-English). Mirror their style — if they write Hinglish, reply in Hinglish. Default is English. Never switch languages mid-reply.
- You deeply understand Indian tax compliance and the challenges of GST/TDS/ITR professionals

## USER CONTEXT
- The user's name and role type are already captured from the registration form before this chat starts.
- Always address the user by their first name from the very first message.
- Use the role to immediately follow the correct qualifying track (see QUALIFYING FLOW below). Never ask the user what type they are — you already know.

## YOUR PRIMARY MISSION
Get the prospect to agree to a free 20-minute product demo. Every conversation moves toward this goal.

## QUALIFYING FLOW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The user's role is already known from the registration form. Use the right track from your very first message.

PRIORITY ORDER DURING QUALIFYING — follow this strictly:

PRIORITY 1 — USER ASKS A QUESTION (any question):
If the user's message contains any question word (how, what, why, can, do, does, is, are, will) OR asks about any feature, product, process, or capability → ANSWER IT COMPLETELY FIRST, then ask the next qualifying question.
This applies regardless of where you are in the qualifying flow. NEVER redirect or delay.
Example: "how can I add clients?" mid-qualifying → full answer about all available methods → "By the way, how many clients do you currently manage?"

PRIORITY 1 EXCEPTION — PRODUCT NOT YET CONFIRMED:
If the question is product-specific (e.g., "how to import clients", "how to migrate", "how to file returns", "how to reconcile", "how to generate Form 16 / TDS certificate", "how to add TAN/GSTIN", "how to create client master") AND the specific product (GST / TDS / ITR) has NOT yet been confirmed in this conversation:
→ Do NOT assume a product. Do NOT answer for just one product.
→ Ask which product they mean in ONE short line, then end with:
QUICK_REPLIES:["Express GST","Express TDS","Express ITR","All three"]
→ Once they reply with a product, answer their original question fully for that product.

PRIORITY 2 — USER IGNORES QUALIFYING AND GIVES NO QUESTION:
If the user gives a short affirmative/deflection with no question ("nothing", "ok", "fine", "not sure") → continue qualifying: ask the next question.

PRIORITY 3 — TRULY VAGUE OPENER (rare):
ONLY if the user sends something like "what do you offer?" or "tell me about your products" with absolutely no specific question, feature, or capability mentioned → redirect: "Let me make sure I point you to exactly the right solution. [next qualifying question]"
This redirect is the EXCEPTION, not the rule. When in doubt, answer.

RULE — IF A QUESTION WAS PREVIOUSLY UNANSWERED:
If the user repeats or follows up on a question that was redirected or not properly answered, they are frustrated. Answer completely, immediately. No redirect.

RULE — CROSS-PRODUCT REDIRECT:
If a user asks about a feature for the wrong product (e.g., "Form 16 in Express GST" — Form 16 is an ITR/TDS feature), do NOT ask "Would you like to know more?" — that forces a useless yes/no exchange. Instead, in ONE response: (1) one sentence clarifying it belongs to the correct product, (2) immediately give the full answer for that correct product from the KB. No follow-up question needed.

Ask ONE qualifying question at a time. After each answer, ask the next.

──────────────────────────────
TRACK A — CA / Tax Professional
──────────────────────────────
Q1: "How many clients are you currently handling compliance for?"
→ End Q1 with: QUICK_REPLIES:["Up to 50 clients","50–200 clients","200+ clients"]

Q2: "Which areas are you filing for them — GST, TDS, ITR, or a mix?"
→ End Q2 with: QUICK_REPLIES:["GST","TDS","ITR","All three"]

Q3: "What's your biggest challenge right now — keeping up with deadlines, reconciliation, client notices, or something else?"
→ End Q3 with: QUICK_REPLIES:["Meeting deadlines","Reconciliation errors","Client notices","Managing multiple clients"]

IMPORTANT: Track A has only 3 questions. Do NOT ask about GSTINs, TAN count, or invoice volume — those are Track B questions for business owners. CAs get Q1, Q2, Q3 only.

IMPORTANT: If the user has already said "All three", "all", or named multiple products at ANY point in the conversation (including when answering a product-specific question), that counts as the answer to Q2. Do NOT ask Q2 again. Move straight to Q3.

Once complete, pitch: bulk client management, auto client emails, single-screen notice dashboard, serve more clients without adding staff.

──────────────────────────────
TRACK B — Business / Enterprise
──────────────────────────────
Q1: "Which compliance are you handling — GST, TDS, ITR, or all three?"
→ End Q1 with: QUICK_REPLIES:["GST","TDS","ITR","All three"]
Q2 — depends on Q1:
  - GST only → "How many GSTINs do you manage, and roughly how many invoices per month?"
  - TDS only → "How many TANs does your business have, and how many deductee entries per quarter?"
  - ITR only → "How many ITRs does your business file in a year?"
  - All three / two or more → Ask about all in one question: "How many GSTINs are you managing, do you have multiple TANs for TDS, and roughly how many ITRs does your business file?"
Q3: "How are you currently managing this — in-house team, through a CA, or some software?"
→ End Q3 with: QUICK_REPLIES:["In-house team","Through a CA","Using software","Manual / Excel"]

IMPORTANT: Track B Q2 sub-questions are ONLY for business owners, never for CAs.
IMPORTANT: When the user says "all three" or mentions multiple compliance areas, treat their product context as all three (GST + TDS + ITR) and pitch the full bundle. Do NOT pick just one.

Once complete, pitch: automation, error detection, no penalties, cloud access, no dependency on any single person.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## PRICING, ABSOLUTE NON-NEGOTIABLE RULE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When ANYONE asks about pricing, cost, fees, subscription, plans, or charges:
→ NEVER give any numbers, ranges, or approximate amounts.
→ ALWAYS redirect to a demo. Use language like:
   "The best way to understand the exact fit and investment is to see it live. A 20-minute demo covers everything. Can I set one up for you?"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## DEMO BOOKING, ALWAYS PUSH
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
After EVERY substantive answer, include one brief demo CTA. Examples:
- "Want to see this live? A demo takes just 20 minutes."
- "Shall I set up a quick walkthrough so you can see exactly how this works?"

When a user agrees to a demo or shows strong interest:
1. Write ONE warm sentence only. Examples: "Perfect! Our team will personally walk you through everything." or "Great choice! Looking forward to connecting you with our team." or "Excellent! Our team will be in touch to set it up."
2. On the NEXT line, emit the token: COLLECT_DEMO_INFO:true

ABSOLUTE RULES for demo booking text:
- Your message must be ONE sentence maximum. Nothing else.
- NEVER mention "booking card", "form", "details", "just a moment", "I'll show you", "fill in", or anything that describes what the website is doing.
- NEVER ask for date, time, phone, or email — the website shows a form automatically.
- Your only job: one warm sentence + the token on a new line. The form appears on its own.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## QUICK REPLY SUGGESTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When helpful, suggest 2 to 3 clickable reply options by ending your message with:
QUICK_REPLIES:["Option A","Option B","Option C"]

Use this especially at the start, after open-ended questions, or when the user seems unsure.
Do NOT include both QUICK_REPLIES and COLLECT_DEMO_INFO in the same message. COLLECT_DEMO_INFO takes priority.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## ESCALATION, HUMAN AGENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
If the user asks to speak to a manager, senior, human, or real person, or repeats the same concern more than twice without resolution:
1. Respond warmly and empathetically: "Of course, let me get our senior team connected with you right away."
2. Offer them a quick callback.
3. End your message with exactly this token on its own line: ESCALATE_TO_HUMAN:true
Do NOT include QUICK_REPLIES or COLLECT_DEMO_INFO in the same message as ESCALATE_TO_HUMAN.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## QUICK CALLBACK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When a user says "can someone call me?" or "I prefer a call" or asks for a callback:
1. Confirm warmly that you are arranging it
2. End your message with: OFFER_CALLBACK:true
Do NOT combine this with ESCALATE_TO_HUMAN.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## PROACTIVE DEMO CARD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
After 2-3 exchanges where the user has shown genuine interest and you have a sense of their needs, show the demo booking card proactively. Do NOT ask "would you like to book a demo?" Just show it:
End your message with: SHOW_DEMO_CARD:true
This is the preferred method. Use COLLECT_DEMO_INFO:true only when the user has explicitly said yes to a demo.
Never ask demo scheduling questions in plain chat. Trigger the demo card instead.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## PRODUCT TABS (multi-product answers)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When the user confirms they need info for ALL THREE products (says "All three", "all", "all products", "all three") AND asks a feature question (import clients, migrate, add clients, client master), respond with ONE brief intro line and then this token:
PRODUCT_TABS:[{"product":"Express GST","items":["item1","item2","item3"]},{"product":"Express TDS","items":["item1","item2","item3"]},{"product":"Express ITR","items":["item1"]}]
Rules:
- Each item = ONE short line describing a method or feature
- The frontend renders this as a clickable tab card, one tab per product
- Do NOT write a flat bullet list when PRODUCT_TABS is used
- Do NOT combine PRODUCT_TABS with QUICK_REPLIES in the same message
- After the token, add one demo CTA sentence

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## YOUR PRODUCTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. **Express GST**, GSTR-1, 3B, 9, 9C filing; 2A/2B reconciliation (no invoice count limit); e-invoice; e-way bill; auto-prepared returns; bulk client management; client master with 4 import methods: (a) GSTIN credentials (single client, auto-fetches all details from GST portal), (b) Excel bulk import (add hundreds of clients at once via template), (c) JSON import (auto-scan or manual), (d) ClearTax migration (one-click import from ClearTax)
2. **Express TDS**, 24Q, 26Q, 27Q, 27EQ filing; TRACES integration; TDS certificates; challan management; FVU generation; client master with 3 import methods: (a) ITD credentials (Income Tax Portal + TRACES credentials, auto-fetches deductor details), (b) Excel bulk import (Deductor Name, TAN, Income Tax password via template), (c) TXT/TDS/Conso file import (browse folder and import)
3. **Express ITR**, ITR-1 to ITR-7; tax audit; AIS/26AS auto-import; e-verification; all income types covered; client master migration via ClearTax only (one-click: enter ClearTax credentials, system auto-fetches PAN details; passwords must be entered manually)

All products run on **Spectrum Cloud**, fully cloud-based, no local system dependency. VAPT certified, ISO-27001 compliant, 2FA, end-to-end encryption. Mobile app available. Bundle = one login, unified client master, single support team.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## COMPETITOR HANDLING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When prospects mention ClearTax, Winman, GEN TDS, CompuTax, Webtel, Tally, or others:
- Acknowledge respectfully, then give ALL key KDK advantages in a single response — do NOT split across multiple messages.
- Cover 4 to 6 differentiators: reconciliations, automation, client management, cloud access, notice handling, pricing model, support — pick what's most relevant to the user's profile.
- Never be dismissive or aggressive. End with a demo CTA.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## CONVERSATION STATE — READ BEFORE EVERY REPLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Always scan the full conversation history before replying. The history is ground truth. Never contradict or redo something that is already done:

- DEMO ALREADY BOOKED: If the history contains a demo booking confirmation, NEVER output COLLECT_DEMO_INFO or SHOW_DEMO_CARD. If the user asks about their demo status, confirm it is booked with the date and time from the history. Say "Yes, your demo is confirmed for [date] at [time]" — not "let me get that set up."
- CALLBACK ALREADY ARRANGED: If the history shows a callback was already requested, do not trigger OFFER_CALLBACK again. Acknowledge it.
- ESCALATION ALREADY RAISED: If the history shows the user was already escalated to a human, do not re-escalate. Acknowledge the existing request.
- USER DETAILS ALREADY KNOWN: Name, email, and role were collected before this conversation started. Never ask for them again.
- PRODUCT CONTEXT: If the user has already told you which product they need (e.g., said "GST" during qualifying), ALL subsequent answers must refer to that product (Express GST). Never respond with a different product (e.g., Express ITR or Express TDS) unless the user explicitly asks about it.
- NEVER APOLOGISE for confusion you did not cause. If the booking or action is clearly in the history, be confident. Do not say "I apologise for the error in my previous message" when no error was made.
- BE CONSISTENT: If you said something in an earlier message, stay consistent with it unless the user has explicitly changed the situation.
- NEVER second-guess the history: If the last assistant message confirmed a demo, that demo is confirmed. Do not contradict it.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## RULES YOU NEVER BREAK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Never give pricing numbers or ranges
- Never make up features not in the knowledge base
- Never give legal or tax advice
- Never go off-topic
- Never be dismissive of competitors
- Never use the em dash or en dash in responses. Write with commas or shorter sentences instead.
- Prefer bullet lists over dense paragraphs when listing 3+ items. Never use more than 6 bullets in a row.
- Never use the terms "DIFM", "DIY", "Do It For Me", or "Do It Yourself" in any response. These are internal labels only. Speak naturally: say "managing filings for multiple clients" or "handling your own compliance" instead.
- NEVER list all products generically when a user asks "what do you offer" or "tell me about your products." Ask the next qualifying question instead.
- NEVER block or redirect a specific feature question. Always answer it, then continue qualifying.
- PRODUCT NAME: The system context message at the top of this conversation tells you exactly which product (Express GST / TDS / ITR) is relevant. Use that product name in every answer. If a KB article mentions a different product, ignore that product name — use the one from the system context.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## HOW TO ANSWER QUESTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TONE RULE — ALWAYS:
This is a chat, not a documentation page. Keep every reply short and conversational. No walls of text. If you can say it in 2 sentences, do not write 6.

RULE 1 — WHAT TYPE OF ANSWER TO GIVE:
Match the answer format to what the user actually asked. There are four types:

TYPE A — HOW-TO (give numbered steps):
User says: "how to", "steps to", "how do I", "walk me through", "procedure for", "process for".
→ Give steps from KB only (see RULE 2). This is the ONLY time you use numbered steps.

EXCEPTION — MULTI-METHOD PROCESSES (use TYPE B instead of TYPE A):
If the KB shows MULTIPLE WAYS to do something (e.g., add clients via GSTIN / Excel bulk import / JSON / ClearTax migration), do NOT pick just one method and give its steps. Instead, list ALL available methods as bullets with a one-line description of each, then demo CTA. This is a SALES HIGHLIGHT — multiple flexible methods is a feature, not just a how-to. Example: "You can add clients in 4 ways: GSTIN credentials (single client, auto-fetches all details), Excel bulk import (add 100s at once), JSON import, or direct ClearTax migration. Want to see it live?"

TYPE B — FEATURE LIST (give a bullet list):
User asks "how many X", "what all X", "what types of X", "list of X", "which X do you support".
→ Give a clean bullet list of ALL the features found in the KB or Sales KB. Do NOT summarize — list every type.
→ Keep each bullet ONE line. Max 8 bullets. If there are more, add "...and a few more — all covered in the demo."
→ Example: "how many GST reconciliations?" → list EVERY reconciliation type available (2A vs Books, 2B vs Books, R1 vs EWB, R1 vs E-Invoice, Books vs R1, Books vs 6A, Books vs EWB, Conflict reports, Annual) — then demo CTA.

TYPE C — SPECIFIC FEATURE CHECK (1-2 sentences):
User names a specific feature and wants to know if it's supported: "do you have X?", "R1 vs EWB?", "does Express TDS support Y?", "can I do X?".
→ Confirm yes/no in 1 sentence + 1 line on what it does. Then demo CTA. NO list, NO steps.
→ Example: "R1 vs Ewabill?" → "Yes, Express GST supports R1 vs E-Way Bill reconciliation — it compares your GSTR-1 filings with EWB data to catch mismatches. Want to see it live?"

TYPE D — GENERAL / OPEN (2-3 sentences max):
Everything else — "tell me about X", "what is Y", general questions.
→ 2-3 sentences. No steps, no bullets unless genuinely listing 3+ items.

RULE 2 — STEP FORMAT (only when steps are explicitly asked):
- Copy steps EXACTLY from the RELEVANT PRODUCT KB ARTICLES. Do not add, invent, reorder, or merge steps.
- "Log in" or "open the software" is NEVER a step unless it is literally written in the KB article.
- Each step = ONE short line. No sub-bullets. No expanding a step into a paragraph.
- Maximum 5 steps shown. If more exist: end with "...a couple more quick steps — easiest to see live in a 20-min demo."
- After the steps, one line demo CTA. Nothing else.

RULE 3 — PARTIAL KNOWLEDGE:
If KB has some info but not complete steps: give 1-2 sentences on what you know, then "For the full walkthrough, a 20-min demo shows this end to end. Want me to set one up?"

RULE 4 — NO KB MATCH:
Say: "Our team can walk you through this directly — best seen live. Want a quick 20-min demo?"
Never invent steps, navigation paths, or feature behaviour.`;

// ── Analyze what was wrong in a bot response ──
async function analyzeWhatWrong(customerQuestion, botResponse) {
  try {
    const prompt = `You are a QA analyst for KDK Software's AI sales chatbot (Express GST, TDS, ITR).

Given the customer's question and the chatbot's response, identify in 1-2 sentences what was wrong or missing in the response. Be specific — e.g. "Bot did not address the specific GSTR form asked about" or "Bot gave a generic answer instead of explaining the feature" or "Bot failed to push for a demo after answering."

Customer question: ${customerQuestion || '(not captured)'}

Chatbot response:
${(botResponse || '').slice(0, 600)}

Write ONLY the issue description. No preamble.`;

    const result = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 100
    });
    return result.choices[0]?.message?.content?.trim() || null;
  } catch(e) {
    console.error('analyzeWhatWrong error:', e.message);
    return null;
  }
}

// ── Reformulate raw feedback into a clean AI-readable rule ──
async function reformulateCorrection(customerQuestion, botResponse, rawFeedback) {
  try {
    const prompt = `You are helping improve the KDK Software Sales Chatbot for KDK Software (Express GST, TDS, ITR products).

A sales team member reviewed a chatbot response and gave raw feedback, it may be in Hindi, English, or mixed, and may be informal or unstructured.

Your job: Convert their feedback into a clear, actionable correction RULE in English that the AI can follow in future conversations.

The rule must:
- Start with "RULE:"
- Be 2-4 sentences max
- Be specific and actionable (tell the AI exactly what to DO, not just what was wrong)
- Include a short example if helpful
- Be in English regardless of feedback language

Context:
Customer question: ${customerQuestion || '(not provided)'}

What Aria responded (the response being corrected):
${(botResponse || '').slice(0, 500)}

Raw feedback from reviewer:
${rawFeedback}

Write ONLY the rule. No preamble, no explanation.`;

    const result = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 180
    });
    return result.choices[0]?.message?.content?.trim() || rawFeedback;
  } catch(e) {
    console.error('Reformulation error:', e.message);
    return rawFeedback;
  }
}

function buildSystemPrompt(retrievedKB, skipKB = false) {
  // skipKB = true during early qualifying phase — no KB needed, saves tokens.
  // When a specific KB article is found, inject it — saves ~10k tokens vs always loading full salesKB.
  // When nothing is retrieved, fall back to the full Sales KB so competitor/objection handling still works.
  let kbSection;
  if (skipKB) {
    kbSection = '';
  } else if (retrievedKB) {
    kbSection = `\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n## RELEVANT PRODUCT KB ARTICLES\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nUse ONLY these for step-by-step guidance. Do NOT invent steps not shown here.\n\n${retrievedKB}`;
  } else {
    kbSection = `\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n## SALES KNOWLEDGE BASE\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n${salesKB}\n\n[No specific KB articles retrieved. Use the Sales KB above for features and competitor handling. Do not invent step-by-step navigation. Drive toward a demo.]`;
  }

  reloadCorrections();
  const correctionSection = correctionsCache
    ? `\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n## APPROVED CORRECTIONS — HIGHEST PRIORITY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nThese are verified corrections from real sales conversations. They OVERRIDE everything else when relevant.\n\n${correctionsCache}`
    : '';

  return BASE_PROMPT + kbSection + correctionSection;
}

// ── PostgreSQL setup ──
let pgPool = null;
if (process.env.DATABASE_URL || process.env.DB_HOST) {
  pgPool = new Pool(
    process.env.DATABASE_URL
      ? { connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } }
      : {
          host:     process.env.DB_HOST,
          port:     parseInt(process.env.DB_PORT || '5432'),
          database: process.env.DB_NAME     || 'postgres',
          user:     process.env.DB_USER     || 'postgres',
          password: process.env.DB_PASSWORD || '',
          ssl: { rejectUnauthorized: false },
        }
  );
  pgPool.query(`CREATE TABLE IF NOT EXISTS chat_logs (
      id           SERIAL PRIMARY KEY,
      session_id   VARCHAR(64),
      user_name    VARCHAR(255),
      user_email   VARCHAR(255),
      user_role    VARCHAR(100),
      user_message TEXT NOT NULL,
      bot_response TEXT NOT NULL,
      flagged      BOOLEAN DEFAULT false,
      correction   TEXT,
      created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`)
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS training_feedback (
      id                   SERIAL PRIMARY KEY,
      session_id           VARCHAR(64),
      submitted_by         VARCHAR(255),
      user_role            VARCHAR(100),
      customer_question    TEXT,
      bot_response_given   TEXT,
      wrong_response_desc  TEXT,
      suggested_correction TEXT NOT NULL,
      status               VARCHAR(20) DEFAULT 'pending',
      reviewed_by          VARCHAR(255),
      review_notes         TEXT,
      created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => pgPool.query(`
      ALTER TABLE training_feedback
        ADD COLUMN IF NOT EXISTS customer_question  TEXT,
        ADD COLUMN IF NOT EXISTS bot_response_given TEXT
    `))
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS leads (
      id              BIGINT PRIMARY KEY,
      name            VARCHAR(255) NOT NULL,
      email           VARCHAR(255),
      phone           VARCHAR(50),
      role            VARCHAR(100),
      type            VARCHAR(50)  DEFAULT 'lead',
      time_preference VARCHAR(100),
      source          VARCHAR(100) DEFAULT 'chat-widget',
      created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS demo_requests (
      id              BIGINT PRIMARY KEY,
      name            VARCHAR(255) NOT NULL,
      email           VARCHAR(255),
      phone           VARCHAR(50),
      company         VARCHAR(255),
      role            VARCHAR(100),
      preferred_date  VARCHAR(100),
      time_preference VARCHAR(100),
      booked_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => pgPool.query(`CREATE TABLE IF NOT EXISTS sessions (
      id         VARCHAR(64) PRIMARY KEY,
      user_data  JSONB DEFAULT '{}',
      messages   JSONB DEFAULT '[]',
      started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      last_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`))
    .then(() => console.log('✅  PostgreSQL connected — tables ready.'))
    .catch(err => console.error('⚠️  PostgreSQL error:', err.message));
}

async function saveLog({ sessionId, userContext, userMessage, botResponse }) {
  if (!pgPool) return;
  try {
    await pgPool.query(
      `INSERT INTO chat_logs (session_id, user_name, user_email, user_role, user_message, bot_response)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [
        sessionId || null,
        userContext?.name  || null,
        userContext?.email || null,
        userContext?.role  || null,
        userMessage,
        botResponse
      ]
    );
  } catch(err) {
    console.error('Log save error:', err.message);
  }
}

// ── Leads storage ──
const LEADS_FILE = path.join(__dirname, 'leads.json');
let leads = [];
try {
  if (fs.existsSync(LEADS_FILE)) leads = JSON.parse(fs.readFileSync(LEADS_FILE, 'utf-8'));
} catch(e) {}

async function saveLead(lead) {
  leads.push(lead);
  if (pgPool) {
    try {
      await pgPool.query(
        `INSERT INTO leads (id, name, email, phone, role, type, time_preference, source)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING`,
        [lead.id, lead.name, lead.email||null, lead.phone||null, lead.role||null,
         lead.type||'lead', lead.timePreference||null, lead.source||'chat-widget']
      );
    } catch(e) { console.error('Lead PG save error:', e.message); }
  } else {
    try { fs.writeFileSync(LEADS_FILE, JSON.stringify(leads, null, 2)); } catch(e) {}
  }
}

// ── Demo requests storage ──
const DEMOS_FILE = path.join(__dirname, 'demo_requests.json');
let demoRequests = [];
try {
  if (fs.existsSync(DEMOS_FILE)) demoRequests = JSON.parse(fs.readFileSync(DEMOS_FILE, 'utf-8'));
} catch(e) {}

async function saveDemo(demo) {
  demoRequests.push(demo);
  if (pgPool) {
    try {
      await pgPool.query(
        `INSERT INTO demo_requests (id, name, email, phone, company, role, preferred_date, time_preference)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING`,
        [demo.id, demo.name, demo.email||null, demo.phone||null, demo.company||null,
         demo.role||null, demo.preferredDate||null, demo.timePreference||null]
      );
    } catch(e) { console.error('Demo PG save error:', e.message); }
  } else {
    try { fs.writeFileSync(DEMOS_FILE, JSON.stringify(demoRequests, null, 2)); } catch(e) {}
  }
}

// ── Sessions storage ──
let sessionStore = {};
try {
  const SESSIONS_FILE = path.join(__dirname, 'sessions.json');
  if (fs.existsSync(SESSIONS_FILE)) {
    const arr = JSON.parse(fs.readFileSync(SESSIONS_FILE, 'utf-8'));
    arr.forEach(s => { sessionStore[s.id] = s; });
  }
} catch(e) {}

async function saveSession(sess) {
  sessionStore[sess.id] = sess;
  if (pgPool) {
    try {
      await pgPool.query(
        `INSERT INTO sessions (id, user_data, messages, started_at, last_at)
         VALUES ($1,$2,$3,$4,$5)
         ON CONFLICT (id) DO UPDATE SET
           user_data  = EXCLUDED.user_data,
           messages   = EXCLUDED.messages,
           last_at    = EXCLUDED.last_at`,
        [sess.id, JSON.stringify(sess.user||{}), JSON.stringify(sess.messages||[]),
         sess.startedAt, sess.lastAt]
      );
    } catch(e) { console.error('Session PG save error:', e.message); }
  }
}

// ── File-based Feedback storage ──
const FEEDBACK_FILE = path.join(__dirname, 'feedback.json');
let feedbackList = [];

try {
  if (fs.existsSync(FEEDBACK_FILE)) {
    feedbackList = JSON.parse(fs.readFileSync(FEEDBACK_FILE, 'utf-8'));
  }
} catch(e) {}

function saveFeedback() {
  try {
    fs.writeFileSync(FEEDBACK_FILE, JSON.stringify(feedbackList, null, 2));
  } catch(e) {}
}

// ── Routes ──

// Chat (streaming SSE)
app.post('/api/chat', async (req, res) => {
  const clientIp = req.ip || req.socket?.remoteAddress || 'unknown';
  if (!checkRateLimit(`chat:${clientIp}`, 60000, 30)) {
    return res.status(429).json({ error: 'Too many requests. Please wait a moment and try again.' });
  }

  const { messages, userContext, sessionId } = req.body;
  if (!Array.isArray(messages)) return res.status(400).json({ error: 'Invalid messages' });

  // Cap message size — prevents oversized inputs from blowing up the context
  const lastMsg = messages[messages.length - 1];
  if (lastMsg?.content && lastMsg.content.length > 2000) {
    lastMsg.content = lastMsg.content.slice(0, 2000);
  }

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');

  // Build context-aware message list
  const contextMessages = [];
  if (userContext && userContext.name) {
    const firstName = userContext.name.split(' ')[0];
    const isCA = userContext.role === 'CA / Tax Professional';
    const roleDesc = isCA
      ? 'a CA / Tax Professional who manages compliance for multiple clients'
      : 'a business owner managing their own company compliance';
    let demoNote = '';
    if (userContext.demoBooked && userContext.bookedDemoDetails) {
      demoNote = ` IMPORTANT: This user has ALREADY BOOKED A DEMO for ${userContext.bookedDemoDetails.date} at ${userContext.bookedDemoDetails.time}. Do NOT output COLLECT_DEMO_INFO or SHOW_DEMO_CARD. Do NOT ask them to fill a demo form. If they ask about their demo status, simply confirm it is booked.`;
    }
    // Detect product context early so productNote is accurate.
    // When last user message is vague (yes/ok/sure), trust the LAST "Express X" in the bot's
    // last message — bots end with the recommended product after a cross-product redirect.
    const lastMsgForDetect = messages[messages.length - 1]?.content || '';
    const VAGUE_DETECT = /^(yes|no|ok|okay|sure|right|yep|yeah|please|go ahead|tell me|show me|more|great|perfect|alright|got it|steps|how|proceed)\b.{0,40}$/i;
    const isVagueEarly = lastMsgForDetect.length <= 40 && VAGUE_DETECT.test(lastMsgForDetect.trim());
    let detectedProduct = detectProductContext(messages);
    if (isVagueEarly) {
      const lastBotMsgEarly = messages.slice().reverse().find(m => m.role === 'assistant')?.content || '';
      const allMentionsEarly = [...lastBotMsgEarly.matchAll(/Express\s+(GST|TDS|ITR)/gi)];
      if (allMentionsEarly.length > 0) {
        detectedProduct = allMentionsEarly[allMentionsEarly.length - 1][1].toUpperCase();
      }
    }
    const productNote = detectedProduct
      ? ` THIS CONVERSATION IS ABOUT Express ${detectedProduct}. Every product answer MUST say "Express ${detectedProduct}" — never Express GST, Express TDS, or Express ITR unless that matches the detected product.`
      : ' The product this user needs has NOT been confirmed yet in this conversation. If they ask a product-specific question (import clients, migrate, file returns, reconcile, Form 16, TDS certificate, add TAN/GSTIN, client master), DO NOT assume a product — ask which product they mean in one line and end with QUICK_REPLIES:["Express GST","Express TDS","Express ITR","All three"].';

    contextMessages.push({
      role: 'user',
      content: `[System context, do not repeat this to the user: The person I am speaking with is ${userContext.name} (address them as "${firstName}"). They are ${roleDesc}. Their email is ${userContext.email}.${demoNote}${productNote} Tailor all responses to their profile.]`
    });

    // Inject Q1 as already asked by the bot (matches the frontend welcome message).
    // The user's first reply is therefore the Q1 answer — go straight to Q2.
    contextMessages.push({
      role: 'assistant',
      content: isCA
        ? `Hi ${firstName}! Great to connect. I'm from KDK Software's Sales Team. Before I walk you through our solutions, I'd love to understand your practice better. How many clients are you currently handling compliance for?`
        : `Hi ${firstName}! Great to connect. I'm from KDK Software's Sales Team. Before I walk you through our solutions, I'd love to understand your needs better. Which compliance areas are you currently handling?`
    });
  }

  try {
    const lastUserMsg = messages[messages.length - 1]?.content || '';

    // Detect if the last user message is a vague follow-up (yes / ok / sure / tell me etc.)
    // In that case the 2-message window loses topic context — enrich with recent bot message instead.
    const VAGUE_REPLY = /^(yes|no|ok|okay|sure|right|yep|yeah|please|go ahead|tell me|show me|more|great|perfect|alright|got it|steps|how|proceed)\b.{0,40}$/i;
    const isVague = lastUserMsg.length <= 40 && VAGUE_REPLY.test(lastUserMsg.trim());

    const prevUserMsgs = messages.slice(-8).filter(m => m.role === 'user');
    const prevUserMsg  = prevUserMsgs.length >= 2 ? prevUserMsgs[prevUserMsgs.length - 2].content : '';

    // A "complete question" is self-contained and specific — it should be used as the retrieval
    // query on its own. Appending the previous user message would pollute retrieval when the user
    // changes topic (e.g., previous message was about clients, current is about GSTR1 books data).
    const IS_COMPLETE_QUESTION = /how\s+(to|do|does|can|many)|what\s+(is|are|types)|process\s+(to|for)|steps?\s+(to|for)|gstr[-\s]?\d|2[467]q|27eq|itr[-\s]?\d|reconcil|e[-\s]?invoice|form[-\s]?16|challan|fvu|ais\b|import\s+\w|export\s+\w/i;
    const isCompleteQuestion = !isVague && IS_COMPLETE_QUESTION.test(lastUserMsg);

    let contextQuery;
    if (isVague) {
      // Enrich query with the last bot message so KB retrieval keeps the right topic
      const lastBotMsg = messages.slice().reverse().find(m => m.role === 'assistant')?.content || '';
      contextQuery = `${prevUserMsg} ${lastBotMsg.slice(0, 300)} ${lastUserMsg}`.trim();
    } else if (isCompleteQuestion) {
      // Self-contained question — use only current message; prev message may be unrelated
      contextQuery = lastUserMsg;
    } else {
      contextQuery = prevUserMsg ? `${prevUserMsg} ${lastUserMsg}` : lastUserMsg;
    }

    // Skip KB retrieval for early qualifying-phase messages — these are simple answers
    // (client count, compliance areas, current software) that need no KB context.
    // Saves an embedding API call + up to ~14k tokens per qualifying exchange.
    const userMsgCount = messages.filter(m => m.role === 'user').length;

    // If the user just replied with a product name (e.g. "Express ITR") to a bot clarification question,
    // the PREVIOUS user message was a feature/process question that still needs a KB answer.
    // Do NOT skip KB retrieval in this case — the original question must be answered from the KB.
    const PRODUCT_REPLY_RE = /^(express\s+)?(gst|tds|itr|all\s+three)\b/i;
    const prevUserHadFeatureQ = /how|what|process|step|enter|fil|reconcil|generat|import|migrat|feature|can\s+i|do\s+you|does\s+it/i.test(prevUserMsg);
    const isProductSelectionReply = PRODUCT_REPLY_RE.test(lastUserMsg.trim()) && prevUserHadFeatureQ;

    const isQualifyingPhase = !isProductSelectionReply
      && userMsgCount <= 3
      && lastUserMsg.length < 150
      && !/how\s+(to|do|does|can|many|much)|what\s+(is|are|types)|gstr[-\s]?\d|2[467]q|27eq|itr[-\s]?\d|reconcil|e[-\s]?invoice|e[-\s]?way\s*bill|traces|form[-\s]?16|challan|fvu|ais\b|cleartax|winman|computax|tally|pricing|cost|plan|subscription/i.test(lastUserMsg);

    // Detect product — if last reply is vague, check bot's last message for a cross-product redirect.
    // Use the LAST "Express X" mentioned in the bot's message: bots end with the recommended product
    // (e.g., "...not applicable in GST. For Express ITR, you can..." → last mention = ITR → use ITR).
    let productContext = detectProductContext(messages);
    if (isVague) {
      const lastBotMsg = messages.slice().reverse().find(m => m.role === 'assistant')?.content || '';
      const allMentions = [...lastBotMsg.matchAll(/Express\s+(GST|TDS|ITR)/gi)];
      if (allMentions.length > 0) {
        const lastMentioned = allMentions[allMentions.length - 1][1].toUpperCase();
        productContext = lastMentioned; // trust the product the bot recommended at the end of its message
      }
    }

    // Retrieve relevant KB articles — hybrid retrieval (embedding + keyword combined)
    let retrievedKB = '';
    if (!isQualifyingPhase) {
      const kbMaxChars = productContext ? 4000 : 5500;
      let queryEmbedding = null;
      if (embeddedArticles.length > 0) {
        try {
          const embRes = await openai.embeddings.create({
            model: 'text-embedding-3-small',
            input: contextQuery,
          });
          queryEmbedding = embRes.data[0].embedding;
        } catch(embErr) {
          console.warn('Embedding call failed, continuing with keyword-only hybrid:', embErr.message);
        }
      }
      // retrieveHybrid runs both embedding and keyword scoring, combined.
      // Falls back to pure keyword when queryEmbedding is null (no embeddings or API error).
      retrievedKB = retrieveHybrid(queryEmbedding, contextQuery, kbMaxChars, productContext);
      if (!retrievedKB) {
        retrievedKB = retrieveByKeyword(contextQuery, kbMaxChars, productContext);
      }
    }

    const stream = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      messages: [
        { role: 'system', content: buildSystemPrompt(retrievedKB, isQualifyingPhase) },
        ...contextMessages,
        ...messages.slice(-12)
      ],
      stream: true,
      temperature: 0.3,
      max_tokens: 500,
      top_p: 0.9,
      frequency_penalty: 0.1,
    });

    let fullResponse = '';
    for await (const chunk of stream) {
      const text = chunk.choices[0]?.delta?.content || '';
      if (text) {
        fullResponse += text;
        res.write(`data: ${JSON.stringify({ text })}\n\n`);
      }
    }
    res.write('data: [DONE]\n\n');
    res.end();

    const userMessage = messages[messages.length - 1]?.content || '';
    saveLog({ sessionId, userContext, userMessage, botResponse: fullResponse });

    if (sessionId) {
      const now = new Date().toISOString();
      if (!sessionStore[sessionId]) {
        sessionStore[sessionId] = { id: sessionId, user: userContext || {}, messages: [], startedAt: now, lastAt: now };
      }
      const sess = sessionStore[sessionId];
      if (userContext?.name && !sess.user?.name) sess.user = userContext;
      const lastTwo = sess.messages.slice(-2);
      if (!lastTwo.some(m => m.role === 'user' && m.content === userMessage)) {
        sess.messages.push({ role: 'user', content: userMessage, ts: now });
        sess.messages.push({ role: 'assistant', content: fullResponse, ts: new Date().toISOString() });
      }
      sess.lastAt = new Date().toISOString();
      saveSession(sess);
    }
  } catch (err) {
    console.error('OpenAI error:', err.message);
    const msg = err.status === 429
      ? 'Too many requests, please wait a moment and try again.'
      : 'Something went wrong. Please try again.';
    res.write(`data: ${JSON.stringify({ error: msg })}\n\n`);
    res.end();
  }
});

// Save lead (pre-chat form)
app.post('/api/save-lead', async (req, res) => {
  const { name, email, role } = req.body;
  if (!name?.trim() || !email?.trim()) {
    return res.status(400).json({ error: 'Name and email are required' });
  }
  const lead = {
    id: Date.now(),
    name: name.trim(),
    email: email.trim().toLowerCase(),
    role: role?.trim() || 'Unknown',
    source: 'chat-widget',
    capturedAt: new Date().toISOString()
  };
  await saveLead(lead);
  console.log(`\n📧 Lead captured: ${lead.name} <${lead.email}> — ${lead.role}`);
  res.json({ success: true, id: lead.id });
});

// Book demo
app.post('/api/book-demo', async (req, res) => {
  const { name, email, phone, company, preferredDate, timePreference, role } = req.body;
  if (!name?.trim() || !phone?.trim()) {
    return res.status(400).json({ error: 'Name and phone are required' });
  }
  const demo = {
    id: Date.now(),
    name: name.trim(),
    email: email?.trim().toLowerCase() || '',
    phone: phone.trim(),
    company: company?.trim() || '',
    role: role?.trim() || '',
    preferredDate: preferredDate || '',
    timePreference: timePreference || 'Not specified',
    bookedAt: new Date().toISOString()
  };
  await saveDemo(demo);
  console.log(`\n📅 Demo booked: ${demo.name} (${demo.phone}) ${demo.email ? '<' + demo.email + '>' : ''} — ${demo.preferredDate} ${demo.timePreference}`);
  res.json({ success: true, id: demo.id });
});

// Callback / escalation request
app.post('/api/request-callback', async (req, res) => {
  const { name, phone, timePreference, type, role } = req.body;
  if (!name?.trim() || !phone?.trim()) {
    return res.status(400).json({ error: 'Name and phone are required' });
  }
  const entry = {
    id: Date.now(),
    name: name.trim(),
    phone: phone.trim(),
    type: type || 'callback',
    role: role || '',
    timePreference: timePreference || 'Not specified',
    source: 'chat-widget',
    requestedAt: new Date().toISOString()
  };
  await saveLead(entry);
  console.log(`\n📞 Callback requested [${entry.type}]: ${entry.name} (${entry.phone})`);
  res.json({ success: true, id: entry.id });
});

// Demo count
app.get('/api/demos/count', async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT COUNT(*) FROM demo_requests');
      return res.json({ count: parseInt(r.rows[0].count) });
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  res.json({ count: demoRequests.length });
});

// All demos (for review)
app.get('/api/demos', requireAdmin, async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM demo_requests ORDER BY booked_at DESC');
      return res.json(r.rows);
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  res.json(demoRequests);
});

// All leads (for review)
app.get('/api/leads', requireAdmin, async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM leads ORDER BY created_at DESC');
      return res.json(r.rows);
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  res.json(leads);
});

// Chat logs (for reviewing bot quality)
app.get('/api/logs', requireAdmin, async (req, res) => {
  if (!pgPool) return res.json({ error: 'PostgreSQL not configured', logs: [] });
  try {
    const limit  = Math.min(parseInt(req.query.limit  || '100'), 500);
    const offset = parseInt(req.query.offset || '0');
    const flagged = req.query.flagged === 'true';

    const where = flagged ? 'WHERE flagged = true' : '';
    const result = await pgPool.query(
      `SELECT id, session_id, user_name, user_role, user_message, bot_response, flagged, correction, created_at
       FROM chat_logs ${where}
       ORDER BY created_at DESC
       LIMIT $1 OFFSET $2`,
      [limit, offset]
    );
    res.json({ count: result.rowCount, logs: result.rows });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Session routes ──
app.get('/api/sessions', requireAdmin, async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM sessions ORDER BY last_at DESC');
      const sessions = r.rows.map(row => ({
        id: row.id, user: row.user_data, messages: row.messages,
        startedAt: row.started_at, lastAt: row.last_at
      }));
      return res.json({ count: sessions.length, sessions });
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  const sessions = Object.values(sessionStore).sort((a, b) => b.lastAt > a.lastAt ? 1 : -1);
  res.json({ count: sessions.length, sessions });
});

app.get('/api/sessions/:id', requireAdmin, async (req, res) => {
  if (pgPool) {
    try {
      const r = await pgPool.query('SELECT * FROM sessions WHERE id = $1', [req.params.id]);
      if (!r.rows.length) return res.status(404).json({ error: 'Not found' });
      const row = r.rows[0];
      return res.json({ id: row.id, user: row.user_data, messages: row.messages,
        startedAt: row.started_at, lastAt: row.last_at });
    } catch(e) { return res.status(500).json({ error: e.message }); }
  }
  const session = sessionStore[req.params.id];
  if (!session) return res.status(404).json({ error: 'Not found' });
  res.json(session);
});

// ── Training Feedback routes ──

// Save training feedback from sales team
app.post('/api/training-feedback', async (req, res) => {
  const { sessionId, submittedBy, userRole, customerQuestion, botResponseGiven, suggestedCorrection } = req.body;
  if (!suggestedCorrection?.trim()) {
    return res.status(400).json({ error: 'Suggested correction is required' });
  }

  const wrongResponseDesc = await analyzeWhatWrong(customerQuestion, botResponseGiven);

  const entry = {
    id: Date.now(),
    sessionId: sessionId || null,
    submittedBy: submittedBy || null,
    userRole: userRole || null,
    customerQuestion: customerQuestion || null,
    botResponseGiven: botResponseGiven || null,
    wrongResponseDesc: wrongResponseDesc || null,
    suggestedCorrection: suggestedCorrection.trim(),
    status: 'pending',
    reviewedBy: null,
    reviewNotes: null,
    createdAt: new Date().toISOString()
  };
  feedbackList.push(entry);
  saveFeedback();
  console.log(`\n📝 Training feedback #${entry.id} by ${submittedBy || 'unknown'}`);

  if (pgPool) {
    pgPool.query(
      `INSERT INTO training_feedback
         (session_id, submitted_by, user_role, customer_question, bot_response_given, wrong_response_desc, suggested_correction)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [sessionId||null, submittedBy||null, userRole||null, customerQuestion||null, botResponseGiven||null, wrongResponseDesc||null, suggestedCorrection.trim()]
    ).catch(err => console.error('PG feedback save error:', err.message));
  }

  res.json({ success: true, id: entry.id });
});

// View all training feedback (admin)
app.get('/api/training-feedback', requireAdmin, async (req, res) => {
  if (!pgPool) {
    const { status } = req.query;
    const allowed = ['pending', 'approved', 'rejected'];
    const list = allowed.includes(status) ? feedbackList.filter(f => f.status === status) : feedbackList;
    return res.json({ count: list.length, feedback: [...list].sort((a, b) => b.id - a.id) });
  }
  try {
    const { status } = req.query;
    const allowed = ['pending', 'approved', 'rejected'];
    const where  = allowed.includes(status) ? 'WHERE status = $1' : '';
    const params = allowed.includes(status) ? [status] : [];
    const result = await pgPool.query(
      `SELECT id, session_id, submitted_by, user_role, customer_question, bot_response_given,
              wrong_response_desc, suggested_correction, status, reviewed_by, review_notes, created_at
       FROM training_feedback ${where} ORDER BY created_at DESC`,
      params
    );
    res.json({ count: result.rowCount, feedback: result.rows });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// Approve or reject a feedback entry
app.post('/api/training-feedback/:id/review', requireAdmin, async (req, res) => {
  const { status, reviewedBy, reviewNotes } = req.body;
  if (!['approved', 'rejected'].includes(status)) {
    return res.status(400).json({ error: 'status must be approved or rejected' });
  }

  if (!pgPool) {
    const id = parseInt(req.params.id);
    const entry = feedbackList.find(f => f.id === id);
    if (!entry) return res.status(404).json({ error: 'Not found' });
    entry.status = status;
    entry.reviewedBy = reviewedBy || null;
    entry.reviewNotes = reviewNotes || null;
    saveFeedback();
    if (status === 'approved') {
      const rule = await reformulateCorrection(entry.customerQuestion, entry.botResponseGiven, entry.suggestedCorrection);
      const date = new Date().toISOString().split('T')[0];
      const by   = reviewedBy ? ` | Reviewed by: ${reviewedBy}` : '';
      const q    = entry.customerQuestion ? `\n**Customer asked:** ${entry.customerQuestion}` : '';
      const b    = entry.botResponseGiven ? `\n**Bot responded:** ${entry.botResponseGiven}` : '';
      const line = `\n---\n\n[Correction #${entry.id} | ${date}${by}]${q}${b}\n**AI Rule:**\n${rule}\n`;
      fs.appendFileSync(CORRECTIONS_FILE, line, 'utf-8');
      console.log(`\n✅ Correction #${entry.id} reformulated and written to corrections.md — live immediately.`);
    }
    return res.json({ success: true });
  }

  try {
    const fetch_result = await pgPool.query('SELECT * FROM training_feedback WHERE id = $1', [req.params.id]);
    if (!fetch_result.rows.length) return res.status(404).json({ error: 'Not found' });
    const entry = fetch_result.rows[0];

    await pgPool.query(
      `UPDATE training_feedback SET status = $1, reviewed_by = $2, review_notes = $3 WHERE id = $4`,
      [status, reviewedBy || null, reviewNotes || null, req.params.id]
    );

    if (status === 'approved') {
      const rule = await reformulateCorrection(entry.customer_question, entry.bot_response_given, entry.suggested_correction);
      const date = new Date().toISOString().split('T')[0];
      const by   = reviewedBy ? ` | Reviewed by: ${reviewedBy}` : '';
      const q    = entry.customer_question  ? `\n**Customer asked:** ${entry.customer_question}` : '';
      const b    = entry.bot_response_given ? `\n**Bot responded:** ${entry.bot_response_given}` : '';
      const line = `\n---\n\n[Correction #${entry.id} | ${date}${by}]${q}${b}\n**AI Rule:**\n${rule}\n`;
      fs.appendFileSync(CORRECTIONS_FILE, line, 'utf-8');
      console.log(`\n✅ Correction #${entry.id} reformulated and written to corrections.md — live immediately.`);
    }

    res.json({ success: true });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// Flag a log entry as wrong and optionally add correction
app.post('/api/logs/:id/flag', requireAdmin, async (req, res) => {
  if (!pgPool) return res.status(503).json({ error: 'PostgreSQL not configured' });
  const { correction } = req.body;
  try {
    await pgPool.query(
      'UPDATE chat_logs SET flagged = true, correction = $1 WHERE id = $2',
      [correction || null, req.params.id]
    );
    res.json({ success: true });
  } catch(err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Voice Transcription (OpenAI Whisper) ──
app.post('/api/voice-transcribe', async (req, res) => {
  const clientIp = req.ip || req.socket?.remoteAddress || 'unknown';
  if (!checkRateLimit(`voice:${clientIp}`, 60000, 10)) {
    return res.status(429).json({ error: 'Too many voice requests. Please wait.' });
  }

  try {
    const { audio, mimeType = 'audio/webm' } = req.body;
    if (!audio) return res.status(400).json({ error: 'No audio data provided' });

    const buffer = Buffer.from(audio, 'base64');
    if (buffer.length > 25 * 1024 * 1024) {
      return res.status(413).json({ error: 'Audio file too large. Maximum size is 25MB.' });
    }
    const ext = mimeType.includes('mp4') ? 'mp4' : mimeType.includes('ogg') ? 'ogg' : 'webm';
    const file = await toFile(buffer, `recording.${ext}`, { type: mimeType });

    const transcription = await openai.audio.transcriptions.create({
      file,
      model: 'whisper-1',
    });

    res.json({ text: transcription.text });
  } catch (e) {
    console.error('Voice transcription error:', e.message);
    res.status(500).json({ error: 'Transcription failed. Please type instead.' });
  }
});

app.post('/api/tts', async (req, res) => {
  const clientIp = req.ip || req.socket?.remoteAddress || 'unknown';
  if (!checkRateLimit(`tts:${clientIp}`, 60000, 20)) {
    return res.status(429).json({ error: 'Too many TTS requests. Please wait.' });
  }

  try {
    const { text } = req.body;
    if (!text) return res.status(400).json({ error: 'No text provided' });
    if (text.length > 1000) return res.status(400).json({ error: 'Text too long for TTS.' });

    const mp3 = await openai.audio.speech.create({
      model: 'tts-1',
      voice: 'nova',   // female, warm, friendly
      input: text,
      speed: 1.0,
    });

    const buffer = Buffer.from(await mp3.arrayBuffer());
    res.set('Content-Type', 'audio/mpeg');
    res.send(buffer);
  } catch (e) {
    console.error('TTS error:', e.message);
    res.status(500).json({ error: 'TTS failed' });
  }
});

// Fallback
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`\n✅  KDK Sales Chatbot is live!`);
  console.log(`   Open: http://localhost:${PORT}\n`);
});
